# Pandas对象

Series：一维数组，与Numpy中的一维array类似。二者与Python基本的数据结构List也很相近，其区别是：List中的元素可以是不同的数据类型，而Array和Series中则只允许存储相同的数据类型，这样可以更有效的使用内存，提高运算效率。
Time- Series：以时间为索引的Series。
DataFrame：二维的表格型数据结构。很多功能与R中的data.frame类似。可以将DataFrame理解为Series的容器。以下的内容主要以DataFrame为主。
Panel ：三维的数组，可以理解为DataFrame的容器


Pandas 本身的内容比较多，和NumPy的关联也非常紧密。在这里我们主要讲常用的两个数据结构(DataFrame和Series)和相应的常用方法属性等。

In [2]:
import numpy as np
import pandas as pd

在pandas的数据结构中，数据对齐是内在的。标签（即索引）和数据之间的链接不会被破坏，除非你显式地进行相关的操作。

## Series

Series数据结构是一种类似于一维数组的对象，是由一组数据（各种Numpy数据类型）以及一组与之相关的标签（即索引）组成。

### 创建Series

多数情况下，Series数据结构是我们直接从DataFrame数据结构中截取出来的，但也可以自己创建Series。语法如下：
```
s = pd.Series(data, index=index)
```

其中data可以是不同的内容：
- 字典
- ndarray
- 标量

index 是轴标签列表，根据不同的情况传入的内容有所不同。

##### 由ndarray构建

如果data是ndarray，则索引的长度必须与数据相同。如果没有入索引，将创建一个值为[0，...，len（data）-1]的索引。

In [2]:
ser = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
ser
#type(ser)

a   -0.311304
b    2.110198
c   -0.221903
d    3.410756
e   -0.602537
dtype: float64

In [3]:
ser.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [6]:
ser.index[[True,False,True,True,True]]

Index(['a', 'c', 'd', 'e'], dtype='object')

In [4]:
pd.Series(np.random.randn(5))

0    0.681424
1   -0.832121
2   -0.173569
3    1.813011
4    0.765119
dtype: float64

In [3]:
np.random.seed(100)
ser=pd.Series(np.random.rand(7))
ser

0    0.543405
1    0.278369
2    0.424518
3    0.844776
4    0.004719
5    0.121569
6    0.670749
dtype: float64

In [4]:
import calendar as cal
monthNames=[cal.month_name[i] for i in np.arange(1,6)]
print (monthNames)
months=pd.Series(np.arange(1,6),index=monthNames);
months

['January', 'February', 'March', 'April', 'May']

January     1
February    2
March       3
April       4
May         5
dtype: int64

In [7]:
months.index

Index(['January', 'February', 'March', 'April', 'May'], dtype='object')

##### 由字典构建

若data是一个dict，如果传递了索引，则索引中与标签对应的数据中的值将被列出。否则，将从dict的排序键构造索引（如果可能）。

In [8]:
d = {'a' : 0., 'b' : 1., 'c' : 2.}
pd.Series(d)

a    0.0
b    1.0
c    2.0
dtype: float64

In [9]:
pd.Series(d, index=['b', 'c', 'd', 'a'])

b    1.0
c    2.0
d    NaN
a    0.0
dtype: float64

In [10]:
stockPrices = {'GOOG':1180.97,'FB':62.57,'TWTR': 64.50, 'AMZN':358.69,'AAPL':500.6}
stockPriceSeries=pd.Series(stockPrices,index=['GOOG','FB','YHOO','TWTR','AMZN','AAPL'],name='stockPrices')
stockPriceSeries

GOOG    1180.97
FB        62.57
YHOO        NaN
TWTR      64.50
AMZN     358.69
AAPL     500.60
Name: stockPrices, dtype: float64

注：NaN(not a number)是Pandas的标准缺失数据标记。

In [11]:
print(stockPriceSeries.name)
stockPriceSeries.index

stockPrices

Index(['GOOG', 'FB', 'YHOO', 'TWTR', 'AMZN', 'AAPL'], dtype='object')

In [12]:
dogSeries=pd.Series('chihuahua',index=['breed','countryOfOrigin','name', 'gender'])
dogSeries

breed              chihuahua
countryOfOrigin    chihuahua
name               chihuahua
gender             chihuahua
dtype: object

##### 由标量创建

如果数据是标量值，则必须提供索引。将该值重复以匹配索引的长度。

In [13]:
pd.Series(5., index=['a', 'b', 'c', 'd', 'e'])

a    5.0
b    5.0
c    5.0
d    5.0
e    5.0
dtype: float64

除了上述之外，类ndarray的对象传入后也会转换为ndarray来创建Series

In [14]:
ser = pd.Series([5,4,2,-3,True])
ser

0       5
1       4
2       2
3      -3
4    True
dtype: object

In [16]:
ser11 = pd.Series([True,True])
ser11

0    True
1    True
dtype: bool

In [15]:
ser.values

array([5, 4, 2, -3, True], dtype=object)

In [16]:
ser.name

In [17]:
ser.index

RangeIndex(start=0, stop=5, step=1)

In [25]:
ser2 = pd.Series([5, 4, 2, -3, True], index=['b', 'e', 'c', 'a', 'd'])
ser2

b       5
e       4
c       2
a      -3
d    True
dtype: object

In [26]:
ser2.index

Index(['b', 'e', 'c', 'a', 'd'], dtype='object')

In [27]:
ser2.values

array([5, 4, 2, -3, True], dtype=object)

### Series is ndarray-like

Series与ndarray非常相似，是大多数NumPy函数的有效参数。包括像切片这样的索引操作。

In [5]:
ser = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
ser

a   -0.231872
b    0.207976
c    0.935808
d    0.179578
e   -0.577162
dtype: float64

In [10]:
ser[0]

C:\Users\bcg28\AppData\Local\Temp\ipykernel_7604\2519058933.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser[0]

np.float64(-0.2318721969038312)

In [7]:
ser[:3]

a   -0.231872
b    0.207976
c    0.935808
dtype: float64

In [8]:
ser[ser > 0]

b    0.207976
c    0.935808
d    0.179578
dtype: float64

In [11]:
ser[ser > ser.median()]

b    0.207976
c    0.935808
dtype: float64

In [12]:
ser[ser > ser.median()]=1
ser

a   -0.231872
b    1.000000
c    1.000000
d    0.179578
e   -0.577162
dtype: float64

In [13]:
ser[[4, 3, 1]]

C:\Users\bcg28\AppData\Local\Temp\ipykernel_7604\707641178.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser[[4, 3, 1]]

e   -0.577162
d    0.179578
b    1.000000
dtype: float64

In [14]:
np.exp(ser)

a    0.793047
b    2.718282
c    2.718282
d    1.196713
e    0.561490
dtype: float64

### Series is dict-like

Series同时也像一个固定大小的dict，可以通过索引标签获取和设置值：

In [15]:
ser

a   -0.231872
b    1.000000
c    1.000000
d    0.179578
e   -0.577162
dtype: float64

In [16]:
ser['a']

np.float64(-0.2318721969038312)

In [17]:
ser['e'] = 12.
ser

a    -0.231872
b     1.000000
c     1.000000
d     0.179578
e    12.000000
dtype: float64

In [28]:
'e' in ser

True

In [29]:
'f' in ser

False

注：如果引用了未包含的标签，则会引发异常：

使用get方法，未包含的索引则会返回None，或者特定值。和dict的操作类似。

In [30]:
print(ser.get('f'))

print(ser.get('a'))

None
-1.991056784055809

In [25]:
ser.get('f', np.nan)

nan

### 矢量化操作&标签对齐

在进行数据分析时，通常没必要去使用循环，而是使用矢量化的操作方式。

In [31]:
ser

a    -1.991057
b     1.000000
c     1.000000
d    -0.430894
e    12.000000
dtype: float64

In [32]:
ser + ser

a    -3.982114
b     2.000000
c     2.000000
d    -0.861788
e    24.000000
dtype: float64

In [33]:
ser * 2

a    -3.982114
b     2.000000
c     2.000000
d    -0.861788
e    24.000000
dtype: float64

In [34]:
np.exp(ser)

a         0.136551
b         2.718282
c         2.718282
d         0.649928
e    162754.791419
dtype: float64

Series和ndarray之间的一个主要区别是，Series之间的操作会自动对齐基于标签的数据。

In [35]:
ser

a    -1.991057
b     1.000000
c     1.000000
d    -0.430894
e    12.000000
dtype: float64

In [36]:
ser[1:] + ser[:-1]

a         NaN
b    2.000000
c    2.000000
d   -0.861788
e         NaN
dtype: float64

未对齐Series之间的操作结果将包含所涉及的索引的并集。如果在其中一个Seires中找不到标签，结果将被标记为NaN。

注意：通常不同索引对象之间的操作的默认结果产生索引的并集，以避免信息丢失。  
因为尽管数据丢失，但拥有索引标签也可以作为计算的重要信息。当然也可以选择通过dropna功能删除丢失数据的标签。

### 属性

名称属性：

In [44]:
s = pd.Series(np.random.randn(5), name='something')

In [35]:
s

0   -0.533373
1   -0.225402
2   -0.314919
3    0.422997
4   -0.438827
Name: something, dtype: float64

In [36]:
s.name

'something'

在多数情况下，series名称会被自动分配，例如在获取1D切片的DataFrame时。（后续DataFrame操作将会讲解到）

In [45]:
s2 = s.rename("different")
s2

0    0.268205
1    2.460114
2   -0.386152
3   -0.136844
4   -0.926731
Name: different, dtype: float64

这里需要注意的是，s和s2是指向不同的对象的。

通过索引属性获取索引

In [46]:
s.index

RangeIndex(start=0, stop=5, step=1)

索引对象也有一个name属性

In [48]:
s.index.name = "index_name"
s

index_name
0    0.268205
1    2.460114
2   -0.386152
3   -0.136844
4   -0.926731
Name: something, dtype: float64

通过值索引获取值

In [40]:
s.values

array([-0.53337271, -0.22540212, -0.31491934,  0.42299678, -0.43882681])

## DataFrame

DataFrame 是可以包含不同类型的列且带索引的二维数据结构，类似于SQL表，或者Series的字典集合。

### 创建DataFrame

DataFrame 是被使用最多的Pandas的对象，和Series类似，创建DataFrame时，也接受许多不同类的参数。

##### From dict of Series or dicts

In [38]:
d = {'one' : pd.Series([1., 2., 3.], index=['a', 'b', 'c']),
     'two' : pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd'])}

In [39]:
df = pd.DataFrame(d)
df

   one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0

In [40]:
pd.DataFrame(d, index=['d', 'b', 'a'])

   one  two
d  NaN  4.0
b  2.0  2.0
a  1.0  1.0

In [41]:
pd.DataFrame(d, index=['d', 'b', 'a'], columns=['two', 'three'])

   two three
d  4.0   NaN
b  2.0   NaN
a  1.0   NaN

可以通过访问索引和列属性分别访问行和列标签。

In [42]:
df.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [43]:
df.columns

Index(['one', 'two'], dtype='object')

##### From dict of ndarrays / lists

ndarrays必须都是相同的长度。如果传递了索引，它的长度也必须与数组一样长。如果没有传递索引，结果将是range(n)，其中n是数组长度。

In [44]:
d = {'one' : [1., 2., 3., 4.],
     'two' : [4., 3., 2.,3]}

In [45]:
pd.DataFrame(d)

   one  two
0  1.0  4.0
1  2.0  3.0
2  3.0  2.0
3  4.0  3.0

In [46]:
pd.DataFrame(d, index=['a', 'b', 'c', 'd'])

   one  two
a  1.0  4.0
b  2.0  3.0
c  3.0  2.0
d  4.0  3.0

##### From structured or record array

这种情况和从数组的字典集合创建是一样的。

In [47]:
np.zeros((2,))

array([0., 0.])

In [48]:
data = np.zeros((2,), dtype=[('A', 'i4'),('B', 'f4'),('C', 'a10')])

In [49]:
data

array([(0, 0., b''), (0, 0., b'')],
      dtype=[('A', '<i4'), ('B', '<f4'), ('C', 'S10')])

In [50]:
data.shape

(2,)

In [51]:
data.size

2

In [52]:
data[:] = [(1,2.,'Hello'), (2,3.,"World")]
data

array([(1, 2., b'Hello'), (2, 3., b'World')],
      dtype=[('A', '<i4'), ('B', '<f4'), ('C', 'S10')])

In [53]:
pd.DataFrame(data, index=['first', 'second'])

        A    B         C
first   1  2.0  b'Hello'
second  2  3.0  b'World'

In [69]:
pd.DataFrame(data, columns=['C', 'A', 'B'])

          C  A    B
0  b'Hello'  1  2.0
1  b'World'  2  3.0

注意：DataFrame和 2-dimensional NumPy ndarray 并不是完全一样的。

除了以上的构造方法之外还有很多其他的构造方法，但获取DataFrame的主要方法是读取表结构的文件，其他构造方法就不一一列出。

In [112]:
df.sub?

In [54]:
d = {'one' : pd.Series([1., 2., 3.], index=['a', 'b', 'c']),'two' : pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
df

   one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0

In [55]:
d = {'one' : pd.Series([1., 2., 3.], index=['a', 'b', 'c']),'two' : pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)
#df
print(df)
print (df.index)
print (df.index.values)
print (type(df.index.values))
print (df.columns)
print (df.columns.values)
print (df.dtypes)
#print (df)

   one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0
Index(['a', 'b', 'c', 'd'], dtype='object')
['a' 'b' 'c' 'd']
<class 'numpy.ndarray'>
Index(['one', 'two'], dtype='object')
['one' 'two']
one    float64
two    float64
dtype: object

In [56]:
stockSummaries={
'AMZN': pd.Series([346.15,0.59,459,0.52,589.8,158.88],index=['Closing price','EPS','Shares Outstanding(M)','Beta', 'P/E','Market Cap(B)']),
'GOOG': pd.Series([1133.43,36.05,335.83,0.87,31.44,380.64],index=['Closing price','EPS','Shares Outstanding(M)','Beta','P/E','Market Cap(B)']),
'FB': pd.Series([61.48,0.59,2450,104.93,150.92],index=['Closing price','EPS','Shares Outstanding(M)','P/E', 'Market Cap(B)']),
'YHOO': pd.Series([34.90,1.27,1010,27.48,0.66,35.36],index=['Closing price','EPS','Shares Outstanding(M)','P/E','Beta', 'Market Cap(B)']),
'TWTR':pd.Series([65.25,-0.3,555.2,36.23],index=['Closing price','EPS','Shares Outstanding(M)','Market Cap(B)']),
'AAPL':pd.Series([501.53,40.32,892.45,12.44,447.59,0.84],index=['Closing price','EPS','Shares Outstanding(M)','P/E','Market Cap(B)','Beta'])}
stockDF=pd.DataFrame(stockSummaries)
stockDF

                         AMZN     GOOG       FB     YHOO    TWTR    AAPL
Beta                     0.52     0.87      NaN     0.66     NaN    0.84
Closing price          346.15  1133.43    61.48    34.90   65.25  501.53
EPS                      0.59    36.05     0.59     1.27   -0.30   40.32
Market Cap(B)          158.88   380.64   150.92    35.36   36.23  447.59
P/E                    589.80    31.44   104.93    27.48     NaN   12.44
Shares Outstanding(M)  459.00   335.83  2450.00  1010.00  555.20  892.45

In [57]:
stockDF=pd.DataFrame(stockSummaries,index=['Closing price','EPS','Shares Outstanding(M)','P/E', 'Market Cap(B)','Beta'])
stockDF

                         AMZN     GOOG       FB     YHOO    TWTR    AAPL
Closing price          346.15  1133.43    61.48    34.90   65.25  501.53
EPS                      0.59    36.05     0.59     1.27   -0.30   40.32
Shares Outstanding(M)  459.00   335.83  2450.00  1010.00  555.20  892.45
P/E                    589.80    31.44   104.93    27.48     NaN   12.44
Market Cap(B)          158.88   380.64   150.92    35.36   36.23  447.59
Beta                     0.52     0.87      NaN     0.66     NaN    0.84

In [58]:
stockDF=pd.DataFrame(stockSummaries,columns=['FB','TWTR','SCNW'])
stockDF

                            FB    TWTR SCNW
Closing price            61.48   65.25  NaN
EPS                       0.59   -0.30  NaN
Market Cap(B)           150.92   36.23  NaN
P/E                     104.93     NaN  NaN
Shares Outstanding(M)  2450.00  555.20  NaN

In [ ]:
#练习：取弄一行和某一列的均值

In [61]:
stockDF1=pd.DataFrame(stockSummaries,columns=['FB'])
print(type(stockDF1))
print(stockDF1)
stockDF1
stockDF1.mean()
print(type(stockDF1.mean()))
stockDF1.mean().values

<class 'pandas.core.frame.DataFrame'>
                            FB
Closing price            61.48
EPS                       0.59
Shares Outstanding(M)  2450.00
P/E                     104.93
Market Cap(B)           150.92
<class 'pandas.core.series.Series'>

array([553.584])

In [62]:
stockDF1=pd.DataFrame(stockSummaries,index=['Closing price'])
stockDF1
stockDF1.values
print(type(stockDF1.values))
stockDF1.values.mean()

<class 'numpy.ndarray'>

357.1233333333333

### DataFrame列操作

DataFrame列的选取，设置和删除列的工作原理与类似的dict操作相同。

In [63]:
d = {'one' : pd.Series([1., 2., 3.], index=['a', 'b', 'c']),'two' : pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(d)

In [64]:
df

   one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0

In [65]:
df['one']

a    1.0
b    2.0
c    3.0
d    NaN
Name: one, dtype: float64

In [66]:
df

   one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0

In [68]:
df['three'] = df['one'] * df['two']
df

   one  two  three
a  1.0  1.0    1.0
b  2.0  2.0    4.0
c  3.0  3.0    9.0
d  NaN  4.0    NaN

In [69]:
df['flag'] = df['one'] > 2
df

   one  two  three   flag
a  1.0  1.0    1.0  False
b  2.0  2.0    4.0  False
c  3.0  3.0    9.0   True
d  NaN  4.0    NaN  False

In [70]:
df['foo'] = 'bar'
df

   one  two  three   flag  foo
a  1.0  1.0    1.0  False  bar
b  2.0  2.0    4.0  False  bar
c  3.0  3.0    9.0   True  bar
d  NaN  4.0    NaN  False  bar

DataFram的列可以像使用dict一样被删除或移出。

In [71]:
del df['two']
df

   one  three   flag  foo
a  1.0    1.0  False  bar
b  2.0    4.0  False  bar
c  3.0    9.0   True  bar
d  NaN    NaN  False  bar

In [72]:
three = df.pop('three')
df

   one   flag  foo
a  1.0  False  bar
b  2.0  False  bar
c  3.0   True  bar
d  NaN  False  bar

In [24]:
df

   one   flag  foo
a  1.0  False  bar
b  2.0  False  bar
c  3.0   True  bar
d  NaN  False  bar

如果传入的是Series并且索引不完全相同，那么会默认按照索引对齐。

In [73]:
df['one_trunc'] = df['one'][:2]
df

   one   flag  foo  one_trunc
a  1.0  False  bar        1.0
b  2.0  False  bar        2.0
c  3.0   True  bar        NaN
d  NaN  False  bar        NaN

也可以插入原始的ndarrays，但其长度必须与DataFrame索引的长度相匹配。

默认情况下，直接的赋值操作列插入到最后的位置。insert方法可用于插入列中的特定位置：

In [74]:
df.insert(1, 'bar', df['one'])

In [75]:
df

   one  bar   flag  foo  one_trunc
a  1.0  1.0  False  bar        1.0
b  2.0  2.0  False  bar        2.0
c  3.0  3.0   True  bar        NaN
d  NaN  NaN  False  bar        NaN

In [77]:
df.insert(column='bar2',loc=2,value='bar2')

In [78]:
df

   one  bar  bar2   flag  foo  one_trunc
a  1.0  1.0  bar2  False  bar        1.0
b  2.0  2.0  bar2  False  bar        2.0
c  3.0  3.0  bar2   True  bar        NaN
d  NaN  NaN  bar2  False  bar        NaN

分配列

In [79]:
import numpy as np
import pandas as pd

In [19]:
df_sample = pd.DataFrame({'A': range(1, 11), 'B': np.random.randn(10)})
df_sample

    A         B
0   1 -0.533373
1   2 -0.225402
2   3 -0.314919
3   4  0.422997
4   5 -0.438827
5   6 -0.501413
6   7 -1.658703
7   8 -1.007577
8   9 -0.508734
9  10  0.781488

In [20]:
#df_sample['A']
df_sample.A

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: A, dtype: int64

In [21]:
df_sample.assign(ln_A = lambda x: np.log(x.A), abs_B = lambda x: np.abs(x.B))

    A         B      ln_A     abs_B
0   1 -0.533373  0.000000  0.533373
1   2 -0.225402  0.693147  0.225402
2   3 -0.314919  1.098612  0.314919
3   4  0.422997  1.386294  0.422997
4   5 -0.438827  1.609438  0.438827
5   6 -0.501413  1.791759  0.501413
6   7 -1.658703  1.945910  1.658703
7   8 -1.007577  2.079442  1.007577
8   9 -0.508734  2.197225  0.508734
9  10  0.781488  2.302585  0.781488

In [87]:
df_sample

    A         B
0   1 -1.641016
1   2 -0.924085
2   3  2.249462
3   4  1.237267
4   5 -0.990713
5   6 -1.314118
6   7 -0.288077
7   8  0.568733
8   9  1.775643
9  10 -0.022471

In [50]:
df_sample.assign?

In [58]:
df_sample

    A         B      ln_A     A_new
0   1  1.180824  0.000000  0.000000
1   2 -0.030112  0.693147  0.693147
2   3  0.864577  1.098612  1.098612
3   4 -0.070219  1.386294  1.386294
4   5 -0.541263  1.609438  1.609438
5   6 -1.370111  1.791759  1.791759
6   7 -1.759243  1.945910  1.945910
7   8 -0.356164  2.079442  2.079442
8   9 -0.170845  2.197225  2.197225
9  10  0.428863  2.302585  2.302585

需要注意的是，传入的参数是以字典类型的方式传入的。如果希望保证顺序的话，可以多次使用assign。

In [89]:
newcol = np.log(df_sample['A'])

In [90]:
newcol

0    0.000000
1    0.693147
2    1.098612
3    1.386294
4    1.609438
5    1.791759
6    1.945910
7    2.079442
8    2.197225
9    2.302585
Name: A, dtype: float64

In [91]:
df_sample.assign(ln_A=newcol)

    A         B      ln_A
0   1  0.652435  0.000000
1   2  1.031452  0.693147
2   3 -1.718626  1.098612
3   4 -0.709013  1.386294
4   5 -0.632182  1.609438
5   6  0.037907  1.791759
6   7 -0.522038  1.945910
7   8  0.131077  2.079442
8   9 -0.698813  2.197225
9  10  0.398334  2.302585

### Indexing / Selection

索引的基础知识如下：

Operation | Syntax | Result
- | - | -
Select column | df[col] | Series
Select row by label | df.loc[label] | Series
Select row by integer location | df.iloc[loc] | Series
Slice rows | df[5:10] | DataFrame
Select rows by boolean vector | df[bool_vec] | DataFrame

In [89]:
df

   one  bar  bar2   flag  foo  one_trunc
a  1.0  1.0  bar2  False  bar        1.0
b  2.0  2.0  bar2  False  bar        2.0
c  3.0  3.0  bar2   True  bar        NaN
d  NaN  NaN  bar2  False  bar        NaN

In [62]:
df.loc['b'][['bar','foo']]
df[['bar','foo']].loc['b']

bar      2
foo    bar
Name: b, dtype: object

In [69]:
#df.loc['b']
df.bar
df.loc['b','bar']
#df.loc['b']['bar']

2.0

关于索引的内容较多，后续单独讲解。

In [73]:
#df.iloc[行位置,列位置]
print( df.iloc[1,1])#选取第二行，第二列的值，返回的为单个值
print (df.iloc[[0,2],:])#选取第一行及第三行的数据
print (df.iloc[0:2,:])#选取第一行到第三行（不包含）的数据
print (df.iloc[:,1])#选取所有记录的第er列的值，返回的为一个Series
print (df.iloc[1,:])#选取第一行数据，返回的为一个Series

2.0
   one  bar  bar2   flag  foo  one_trunc
a  1.0  1.0  bar2  False  bar        1.0
c  3.0  3.0  bar2   True  bar        NaN
   one  bar  bar2   flag  foo  one_trunc
a  1.0  1.0  bar2  False  bar        1.0
b  2.0  2.0  bar2  False  bar        2.0
a    1.0
b    2.0
c    3.0
d    NaN
Name: bar, dtype: float64
one              2
bar              2
bar2          bar2
flag         False
foo            bar
one_trunc        2
Name: b, dtype: object

In [176]:
df

          A         B         C         D
0  1.012952 -0.838197 -1.041325 -0.087286
1  1.153089  1.067939  0.570342 -0.272996
2 -0.160398 -0.013020  0.621867  1.374179
3  0.779654 -1.554635 -1.764824 -0.668985
4  1.741086  0.073530  0.075900 -0.196167
5 -0.425291  0.632212 -0.010632 -0.599132
6  0.904726 -1.396727  1.953033  0.896697
7  0.210418 -0.389813  2.952016 -1.144328
8 -0.873981 -0.831607  0.084170  1.189525
9  0.544333  0.102546  0.252580 -2.827363

注意：在Pandas 0.20版本开始就不推荐使用.ix，只推荐使用基于标签的索引.loc 和基于位置的索引.iloc 。

### 数据对齐和运算

DataFrame对象之间在列和索引（行标签）之间自动数据对齐。并且，运算的结果对象是列和行标签的并集。

In [23]:
df = pd.DataFrame(np.random.randn(10, 4), columns=['A', 'B', 'C', 'D'])
df

          A         B         C         D
0 -0.654381  0.041172 -0.201917 -0.870813
1  0.228932 -0.408040 -0.103925  1.567179
2  0.497025  1.155872  1.838612  1.535727
3  0.254998 -0.844157 -0.982943 -0.306098
4  0.838501 -1.690848  1.151174 -1.029337
5 -0.510992 -2.360271  0.103595  1.738818
6  1.241876  0.132413  0.577794 -1.575906
7 -1.292794 -0.659920 -0.874005 -0.689551
8 -0.535480  1.527953  0.647206 -0.677337
9 -0.265019  0.746106 -3.130785  0.059622

In [24]:
df2 = pd.DataFrame(np.random.randn(7, 3), columns=['A', 'B', 'C'])
df2

          A         B         C
0 -0.875211  1.064878 -0.573153
1 -0.803278  1.092972  0.651278
2  2.160525 -0.639130 -0.333688
3 -0.437602 -1.905795 -1.229019
4  0.794899 -1.160508  0.546056
5  1.163258  0.658877  0.523689
6  1.327156  1.112524 -1.074630

In [26]:
df + df2

          A         B         C   D
0 -1.529592  1.106051 -0.775070 NaN
1 -0.574346  0.684932  0.547352 NaN
2  2.657550  0.516742  1.504924 NaN
3 -0.182604 -2.749952 -2.211963 NaN
4  1.633399 -2.851356  1.697229 NaN
5  0.652266 -1.701394  0.627284 NaN
6  2.569032  1.244937 -0.496836 NaN
7       NaN       NaN       NaN NaN
8       NaN       NaN       NaN NaN
9       NaN       NaN       NaN NaN

In [25]:
df2+df

          A         B         C   D
0 -1.529592  1.106051 -0.775070 NaN
1 -0.574346  0.684932  0.547352 NaN
2  2.657550  0.516742  1.504924 NaN
3 -0.182604 -2.749952 -2.211963 NaN
4  1.633399 -2.851356  1.697229 NaN
5  0.652266 -1.701394  0.627284 NaN
6  2.569032  1.244937 -0.496836 NaN
7       NaN       NaN       NaN NaN
8       NaN       NaN       NaN NaN
9       NaN       NaN       NaN NaN

在DataFrame和Series之间进行操作时，默认行为是使DataFrame列上的Series索引对齐，从而逐行广播。

In [98]:
df.iloc[0]

A    0.999571
B   -0.750643
C    0.454173
D   -0.433419
Name: 0, dtype: float64

In [101]:
df

          A         B         C         D
0  0.999571 -0.750643  0.454173 -0.433419
1  0.635493 -0.411205  0.362960  1.175223
2  1.455082 -1.161002 -0.582895  1.263405
3  0.188312  0.476972 -2.883127  1.103144
4  0.878678 -0.467818 -0.473246 -1.123255
5  1.785819  2.339326 -0.735250 -0.209577
6  1.328820 -0.005883 -0.735784  0.261042
7 -0.183711  1.476428  1.302312  0.180221
8  0.070002  1.583271  1.348411  0.209028
9  2.351481  0.587120  1.189288  0.062038

In [102]:
df - df.iloc[0]

          A         B         C         D
0  0.000000  0.000000  0.000000  0.000000
1 -0.364078  0.339438 -0.091213  1.608642
2  0.455511 -0.410359 -1.037068  1.696824
3 -0.811259  1.227615 -3.337300  1.536563
4 -0.120893  0.282825 -0.927419 -0.689836
5  0.786248  3.089969 -1.189422  0.223842
6  0.329249  0.744760 -1.189956  0.694461
7 -1.183282  2.227071  0.848139  0.613640
8 -0.929569  2.333914  0.894238  0.642447
9  1.351909  1.337763  0.735115  0.495457

In [105]:
#df - df.iloc[[0,1]]

在使用时间序列数据等一些特殊情况下，也可以以列方式进行广播：

In [86]:
index = pd.date_range('1/1/2000', periods=8)
df = pd.DataFrame(np.random.randn(8, 3), index=index, columns=list('ABC'))
df

                   A         B         C
2000-01-01 -0.849415 -0.348923  0.318394
2000-01-02 -0.049114 -1.832510  0.307122
2000-01-03 -0.145051  0.220593 -1.245816
2000-01-04 -0.943359  0.275904 -1.474495
2000-01-05 -0.358119  0.002250  0.779026
2000-01-06  1.128961 -1.705117 -0.335175
2000-01-07  1.152392 -1.115703 -0.929588
2000-01-08  0.673785  0.997088 -1.520089

In [88]:
df.sub(df["A"],axis='columns')

              A         B         C
2000-01-01  0.0  0.500492  1.167809
2000-01-02  0.0 -1.783397  0.356236
2000-01-03  0.0  0.365644 -1.100765
2000-01-04  0.0  1.219263 -0.531136
2000-01-05  0.0  0.360369  1.137145
2000-01-06  0.0 -2.834078 -1.464136
2000-01-07  0.0 -2.268095 -2.081980
2000-01-08  0.0  0.323303 -2.193874

In [90]:
df.sub?

In [114]:
df.sub(df['A'], axis=0)

              A         B         C
2000-01-01  0.0 -0.203128  0.750911
2000-01-02  0.0 -0.085150 -0.582747
2000-01-03  0.0  0.112599  0.259977
2000-01-04  0.0  0.752312  0.157787
2000-01-05  0.0 -0.210188  0.885651
2000-01-06  0.0 -1.667556 -1.665186
2000-01-07  0.0 -0.229123  0.828379
2000-01-08  0.0 -0.588500  0.915357

逻辑运算，与NumPy相似。

In [91]:
df1 = pd.DataFrame({'a' : [1, 0, 1], 'b' : [0, 1, 1] }, dtype=bool)
df2 = pd.DataFrame({'a' : [0, 1, 1], 'b' : [1, 1, 0] }, dtype=bool)

In [92]:
df1

       a      b
0   True  False
1  False   True
2   True   True

In [93]:
df2

       a      b
0  False   True
1   True   True
2   True  False

In [97]:
df1 & df2

       a      b
0  False  False
1  False   True
2   True  False

In [95]:
df1 | df2

      a     b
0  True  True
1  True  True
2  True  True

In [96]:
df1 ^ df2

       a      b
0   True   True
1   True  False
2  False   True

In [120]:
df1

       a      b
0   True  False
1  False   True
2   True   True

In [116]:
-df1  # ~df1

       a      b
0  False   True
1   True  False
2  False  False

转置

In [199]:
df[:5].T

   2000-01-01  2000-01-02  2000-01-03  2000-01-04  2000-01-05
A   -1.004956    0.311926   -1.046797    0.757750   -1.048832
B    0.798252   -2.357152    0.262455    0.263729    0.259480
C    0.287757    0.522861   -0.705939    0.314355    0.968639

### DataFrame & ufunc

由于DataFrame基于NumPy构建，可以直接使用大量NumPy中ufunc函数。

In [122]:
np.exp(df)

                   A          B         C
2000-01-01  3.564469   3.148548  0.998840
2000-01-02  0.511046   1.298460  1.568828
2000-01-03  1.420346   0.467626  1.674395
2000-01-04  0.327988  29.609243  0.877787
2000-01-05  0.724115   2.238231  2.693906
2000-01-06  0.329842   0.467134  0.027282
2000-01-07  0.322628   0.714269  2.357418
2000-01-08  3.155478   2.232618  0.746727

In [123]:
np.asarray(df)

array([[  1.27101522e+00,   1.14694131e+00,  -1.16116021e-03],
       [ -6.71295385e-01,   2.61178980e-01,   4.50328970e-01],
       [  3.50900567e-01,  -7.60086435e-01,   5.15452037e-01],
       [ -1.11477887e+00,   3.38808657e+00,  -1.30351322e-01],
       [ -3.22805025e-01,   8.05685662e-01,   9.90992182e-01],
       [ -1.10914206e+00,  -7.61139444e-01,  -3.60151878e+00],
       [ -1.13125518e+00,  -3.36495221e-01,   8.57566894e-01],
       [  1.14914008e+00,   8.03174713e-01,  -2.92055344e-01]])

# 基本功能

## 数据IO

In [90]:
import numpy as np
import pandas as pd

In [91]:
df = pd.read_csv('data/macrodata.csv')
#df = pd.read_table('data/macrodata.csv')

In [2]:
pd.read_csv?

In [92]:
df

,year,quarter,realgdp,realcons,realinv,realgovt,realdpi,cpi,m1,tbilrate,unemp,pop,infl,realint
0,1959.0,1.0,2710.349,1707.4,286.898,470.045,1886.9,28.980,139.7,2.82,5.8,177.146,0.00,0.00
1,1959.0,2.0,2778.801,1733.7,310.859,481.301,1919.7,29.150,141.7,3.08,5.1,177.830,2.34,0.74
2,1959.0,3.0,2775.488,1751.8,289.226,491.260,1916.4,29.350,140.5,3.82,5.3,178.657,2.74,1.09
3,1959.0,4.0,2785.204,1753.7,299.356,484.052,1931.3,29.370,140.0,4.33,5.6,179.386,0.27,4.06
4,1960.0,1.0,2847.699,1770.5,331.722,462.199,1955.5,29.540,139.6,3.50,5.2,180.007,2.31,1.19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,2008.0,3.0,13324.600,9267.7,1990.693,991.551,9838.3,216.889,1474.7,1.17,6.0,305.270,-3.16,4.33
199,2008.0,4.0,13141.920,9195.3,1857.661,1007.273,9920.4,212.174,1576.5,0.12,6.9,305.952,-8.79,8.91
200,2009.0,1.0,12925.410,9209.2,1558.494,996.287,9926.4,212.671,1592.8,0.22,8.1,306.547,0.94,-0.71
201,2009.0,2.0,12901.504,9189.0,1456.678,1023.528,10077.5,214.469,1653.6,0.18,9.2,307.226,3.37,-3.19
202,2009.0,3.0,12990.341,9256.0,1486.398,1044.088,10040.6,216.385,1673.9,0.12,9.6,308.013,3.56,-3.44

In [93]:
pd.read_table?

In [96]:
#df.head()
#df.tail()
df.shape

(203, 14)

In [97]:

print(df.index)
print(df.columns)
print(df.dtypes)

RangeIndex(start=0, stop=203, step=1)
Index(['year', 'quarter', 'realgdp', 'realcons', 'realinv', 'realgovt',
       'realdpi', 'cpi', 'm1', 'tbilrate', 'unemp', 'pop', 'infl', 'realint'],
      dtype='object')
year        float64
quarter     float64
realgdp     float64
realcons    float64
realinv     float64
realgovt    float64
realdpi     float64
cpi         float64
m1          float64
tbilrate    float64
unemp       float64
pop         float64
infl        float64
realint     float64
dtype: object

Operation | Syntax | Result
- | - | -
Select column | df[col] | Series
Select row by label | df.loc[label] | Series
Select row by integer location | df.iloc[loc] | Series
Slice rows | df[5:10] | DataFrame
Select rows by boolean vector | df[bool_vec] | DataFrame

In [ ]:
df.iloc[行位置,列位置]
#print( df.iloc[1,1])#选取第二行，第二列的值，返回的为单个值
#print (df.iloc[[0,2],:])#选取第一行及第三行的数据
#print (df.iloc[0:2,:])#选取第一行到第三行（不包含）的数据
#print (df.iloc[:,1])#选取所有记录的第er列的值，返回的为一个Series
#print (df.iloc[1,:])#选取第一行数据，返回的为一个Series

In [98]:
df[df.year==1959]
#df.year==1959

,year,quarter,realgdp,realcons,realinv,realgovt,realdpi,cpi,m1,tbilrate,unemp,pop,infl,realint
0,1959.0,1.0,2710.349,1707.4,286.898,470.045,1886.9,28.98,139.7,2.82,5.8,177.146,0.00,0.00
1,1959.0,2.0,2778.801,1733.7,310.859,481.301,1919.7,29.15,141.7,3.08,5.1,177.830,2.34,0.74
2,1959.0,3.0,2775.488,1751.8,289.226,491.260,1916.4,29.35,140.5,3.82,5.3,178.657,2.74,1.09
3,1959.0,4.0,2785.204,1753.7,299.356,484.052,1931.3,29.37,140.0,4.33,5.6,179.386,0.27,4.06

In [99]:
df[df.year==1959][['m1','pop']]
#df.loc[df.year==1959,['m1','pop']]
#df[['m1','pop']][df.year==1959]
#df[['m1','pop']].loc[df.year==1959]

      m1      pop
0  139.7  177.146
1  141.7  177.830
2  140.5  178.657
3  140.0  179.386

### 读取CSV/文本类文件

In [28]:
df = pd.read_csv('data/macrodata.csv')
#df.head()
#df.tail()
df.describe().T

,count,mean,std,min,25%,50%,75%,max
year,203.0,1983.876847,14.686817,1959.000,1971.0000,1984.000,1996.5000,2009.000
quarter,203.0,2.492611,1.118563,1.000,1.5000,2.000,3.0000,4.000
realgdp,203.0,7221.171901,3214.956044,2710.349,4440.1035,6559.594,9629.3465,13415.266
realcons,203.0,4825.293103,2313.346192,1707.400,2874.1000,4299.900,6398.1500,9363.600
realinv,203.0,1012.863862,585.102267,259.764,519.1475,896.210,1436.6815,2264.721
realgovt,203.0,663.328640,140.863655,460.400,527.9595,662.412,773.0490,1044.088
realdpi,203.0,5310.540887,2423.515977,1886.900,3276.9500,4959.400,6977.8500,10077.500
cpi,203.0,105.075788,61.278878,28.980,41.0500,104.100,159.6500,218.610
m1,203.0,667.927586,455.346381,139.600,228.6500,540.900,1102.1000,1673.900
tbilrate,203.0,5.311773,2.803071,0.120,3.5150,5.010,6.6650,15.330
unemp,203.0,5.884729,1.458574,3.400,4.9000,5.700,6.8000,10.700
pop,203.0,239.724153,37.390450,177.146,208.6310,236.348,271.7215,308.013
infl,203.0,3.961330,3.253216,-8.790,2.2700,3.240,4.9750,14.620
realint,203.0,1.336502,2.668799,-6.790,-0.0850,1.340,2.6300,10.950

In [29]:
df.head(10)

,year,quarter,realgdp,realcons,realinv,realgovt,realdpi,cpi,m1,tbilrate,unemp,pop,infl,realint
0,1959.0,1.0,2710.349,1707.4,286.898,470.045,1886.9,28.98,139.7,2.82,5.8,177.146,0.00,0.00
1,1959.0,2.0,2778.801,1733.7,310.859,481.301,1919.7,29.15,141.7,3.08,5.1,177.830,2.34,0.74
2,1959.0,3.0,2775.488,1751.8,289.226,491.260,1916.4,29.35,140.5,3.82,5.3,178.657,2.74,1.09
3,1959.0,4.0,2785.204,1753.7,299.356,484.052,1931.3,29.37,140.0,4.33,5.6,179.386,0.27,4.06
4,1960.0,1.0,2847.699,1770.5,331.722,462.199,1955.5,29.54,139.6,3.50,5.2,180.007,2.31,1.19
5,1960.0,2.0,2834.390,1792.9,298.152,460.400,1966.1,29.55,140.2,2.68,5.2,180.671,0.14,2.55
6,1960.0,3.0,2839.022,1785.8,296.375,474.676,1967.8,29.75,140.9,2.36,5.6,181.528,2.70,-0.34
7,1960.0,4.0,2802.616,1788.2,259.764,476.434,1966.6,29.84,141.1,2.29,6.3,182.287,1.21,1.08
8,1961.0,1.0,2819.264,1787.7,266.405,475.854,1984.5,29.81,142.1,2.37,6.8,182.992,-0.40,2.77
9,1961.0,2.0,2872.005,1814.3,286.246,480.328,2014.4,29.92,142.9,2.29,7.0,183.691,1.47,0.81

In [30]:
#df = pd.read_csv('data/macrodata.csv')

#df.tail()

df['year_str']=df['year'].astype('object')
df.head()
#print(df.dtypes)
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
year,203.0,NaN,NaN,NaN,1983.876847,14.686817,1959.000,1971.0000,1984.000,1996.5000,2009.000
quarter,203.0,NaN,NaN,NaN,2.492611,1.118563,1.000,1.5000,2.000,3.0000,4.000
realgdp,203.0,NaN,NaN,NaN,7221.171901,3214.956044,2710.349,4440.1035,6559.594,9629.3465,13415.266
realcons,203.0,NaN,NaN,NaN,4825.293103,2313.346192,1707.400,2874.1000,4299.900,6398.1500,9363.600
realinv,203.0,NaN,NaN,NaN,1012.863862,585.102267,259.764,519.1475,896.210,1436.6815,2264.721
realgovt,203.0,NaN,NaN,NaN,663.328640,140.863655,460.400,527.9595,662.412,773.0490,1044.088
realdpi,203.0,NaN,NaN,NaN,5310.540887,2423.515977,1886.900,3276.9500,4959.400,6977.8500,10077.500
cpi,203.0,NaN,NaN,NaN,105.075788,61.278878,28.980,41.0500,104.100,159.6500,218.610
m1,203.0,NaN,NaN,NaN,667.927586,455.346381,139.600,228.6500,540.900,1102.1000,1673.900
tbilrate,203.0,NaN,NaN,NaN,5.311773,2.803071,0.120,3.5150,5.010,6.6650,15.330
unemp,203.0,NaN,NaN,NaN,5.884729,1.458574,3.400,4.9000,5.700,6.8000,10.700
pop,203.0,NaN,NaN,NaN,239.724153,37.390450,177.146,208.6310,236.348,271.7215,308.013
infl,203.0,NaN,NaN,NaN,3.961330,3.253216,-8.790,2.2700,3.240,4.9750,14.620
realint,203.0,NaN,NaN,NaN,1.336502,2.668799,-6.790,-0.0850,1.340,2.6300,10.950
year_str,203.0,51.0,1959.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [113]:
i="realint"

IQR=(df[i].quantile(q=0.75)-df[i].quantile(q=0.25))
upper=df[i].quantile(q=0.75)+IQR*1.5
downer=df[i].quantile(q=0.25)-IQR*1.5
#print(sum(df[i]>upper))
#print(sum(df[i]<downer))
upper_flag=df[i]>upper
downer_flag=df[i]<downer

df[i].iloc[upper_flag]=upper
df[i].iloc[downer_flag]=downer


df.describe(include='all').T

<ipython-input-113-5b2399b0806c>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i][upper_flag]=upper
<ipython-input-113-5b2399b0806c>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i][downer_flag]=downer

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
year,203.0,NaN,NaN,NaN,1983.876847,14.686817,1959.0000,1971.0000,1984.000,1996.5000,2009.0000
quarter,203.0,NaN,NaN,NaN,2.492611,1.118563,1.0000,1.5000,2.000,3.0000,4.0000
realgdp,203.0,NaN,NaN,NaN,7221.171901,3214.956044,2710.3490,4440.1035,6559.594,9629.3465,13415.2660
realcons,203.0,NaN,NaN,NaN,4825.293103,2313.346192,1707.4000,2874.1000,4299.900,6398.1500,9363.6000
realinv,203.0,NaN,NaN,NaN,1012.863862,585.102267,259.7640,519.1475,896.210,1436.6815,2264.7210
realgovt,203.0,NaN,NaN,NaN,663.328640,140.863655,460.4000,527.9595,662.412,773.0490,1044.0880
realdpi,203.0,NaN,NaN,NaN,5310.540887,2423.515977,1886.9000,3276.9500,4959.400,6977.8500,10077.5000
cpi,203.0,NaN,NaN,NaN,105.075788,61.278878,28.9800,41.0500,104.100,159.6500,218.6100
m1,203.0,NaN,NaN,NaN,667.927586,455.346381,139.6000,228.6500,540.900,1102.1000,1673.9000
tbilrate,203.0,NaN,NaN,NaN,5.311773,2.803071,0.1200,3.5150,5.010,6.6650,15.3300
unemp,203.0,NaN,NaN,NaN,5.884729,1.458574,3.4000,4.9000,5.700,6.8000,10.7000
pop,203.0,NaN,NaN,NaN,239.724153,37.390450,177.1460,208.6310,236.348,271.7215,308.0130
infl,203.0,NaN,NaN,NaN,3.961330,3.253216,-8.7900,2.2700,3.240,4.9750,14.6200
realint,203.0,NaN,NaN,NaN,1.301219,2.425433,-4.1575,-0.0850,1.340,2.6300,6.7025
year_str,203.0,51.0,1984.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 练习：自定义函数:处理所有离群值

In [27]:
df.columns.values

array(['A', 'B', 'C', 'D'], dtype=object)

In [180]:
df[i].dtypes=='float64'

True

In [178]:
i="realint"

df[i+'_zscore']=(df[i]-df[i].mean())/df[i].std()
print(df[i+'_zscore'].describe())

upper_flag=zscore>3
downer_flag=zscore<-3

df[i+'_zscore'].loc[upper_flag]=3
df[i+'_zscore'].loc[downer_flag]=-3

print(df[i+'_zscore'].describe())

count    2.030000e+02
mean    -1.946992e-16
std      1.000000e+00
min     -3.045004e+00
25%     -5.326376e-01
50%      1.310529e-03
75%      4.846741e-01
max      3.602182e+00
Name: realint_zscore, dtype: float64
count    203.000000
mean      -0.004733
std        0.982932
min       -3.000000
25%       -0.532638
50%        0.001311
75%        0.484674
max        3.000000
Name: realint_zscore, dtype: float64

In [174]:
i="realint"
i+'_zscore'

'realint_zscore'

In [50]:
#错误
sum(list(upper_flag) or list(downer_flag)) 
#sum(list(downer_flag))

6

In [53]:
[True,True] or [False,False,False,False]

[True, True]

In [39]:
sum(upper_flag | downer_flag)

11

In [41]:
sum(upper_flag)
sum(downer_flag)

5

In [321]:
df.quantile?

In [29]:
df["realint"].quantile(q=0.5)

1.34

In [62]:
df.shape

(203, 14)

In [ ]:
#练习图区bikes

In [207]:
df['qtr']=df['year']*10+df['quarter']
df.head(3)

,year,quarter,realgdp,realcons,realinv,realgovt,realdpi,cpi,m1,tbilrate,unemp,pop,infl,realint,qtr
0,1959.0,1.0,2710.349,1707.4,286.898,470.045,1886.9,28.98,139.7,2.82,5.8,177.146,0.00,0.00,19591.0
1,1959.0,2.0,2778.801,1733.7,310.859,481.301,1919.7,29.15,141.7,3.08,5.1,177.830,2.34,0.74,19592.0
2,1959.0,3.0,2775.488,1751.8,289.226,491.260,1916.4,29.35,140.5,3.82,5.3,178.657,2.74,1.09,19593.0

In [210]:
#df.mean()
df.apply(lambda x: x.max() - x.min())

year           50.000
quarter         3.000
realgdp     10704.917
realcons     7656.200
realinv      2004.957
realgovt      583.688
realdpi      8190.600
cpi           189.630
m1           1534.300
tbilrate       15.210
unemp           7.300
pop           130.867
infl           23.410
realint        17.740
qtr           502.000
dtype: float64

In [134]:
df.apply?

In [212]:
#df.quantile?
df.quantile()

In [213]:
#df.mean()#计算列的平均值，参数为轴，可选值为0或1.默认为0，即按照列运算
#df.mean(0)
#df.mean(1)[1:10]
df.sum()
#df.sum(1)#计算行的和
#df.apply(lambda x: x.max() - x.min())#将一个函数应用到DataFrame的每一列，这里使用的是匿名lambda函数，与R中apply函数类似

year         402727.000
quarter         506.000
realgdp     1465897.896
realcons     979534.500
realinv      205611.364
realgovt     134655.714
realdpi     1078039.800
cpi           21330.385
m1           135589.300
tbilrate       1078.290
unemp          1194.600
pop           48664.003
infl            804.150
realint         271.310
qtr         4027776.000
dtype: float64

In [164]:
df.describe().T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
year,203,NaN,NaN,NaN,1983.88,14.6868,1959,1971,1984,1996.5,2009
quarter,203,NaN,NaN,NaN,2.49261,1.11856,1,1.5,2,3,4
realgdp,203,NaN,NaN,NaN,7221.17,3214.96,2710.35,4440.1,6559.59,9629.35,13415.3
realcons,203,NaN,NaN,NaN,4825.29,2313.35,1707.4,2874.1,4299.9,6398.15,9363.6
realinv,203,NaN,NaN,NaN,1012.86,585.102,259.764,519.148,896.21,1436.68,2264.72
realgovt,203,NaN,NaN,NaN,663.329,140.864,460.4,527.96,662.412,773.049,1044.09
realdpi,203,NaN,NaN,NaN,5310.54,2423.52,1886.9,3276.95,4959.4,6977.85,10077.5
cpi,203,NaN,NaN,NaN,105.076,61.2789,28.98,41.05,104.1,159.65,218.61
m1,203,NaN,NaN,NaN,667.928,455.346,139.6,228.65,540.9,1102.1,1673.9
tbilrate,203,NaN,NaN,NaN,5.31177,2.80307,0.12,3.515,5.01,6.665,15.33
unemp,203,NaN,NaN,NaN,5.88473,1.45857,3.4,4.9,5.7,6.8,10.7
pop,203,NaN,NaN,NaN,239.724,37.3904,177.146,208.631,236.348,271.721,308.013
infl,203,NaN,NaN,NaN,3.96133,3.25322,-8.79,2.27,3.24,4.975,14.62
realint,203,NaN,NaN,NaN,1.3365,2.6688,-6.79,-0.085,1.34,2.63,10.95
year_int,203,NaN,NaN,NaN,1983.88,14.6868,1959,1971,1984,1996.5,2009
year_str,203,51,1982.0,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#练习：有没有离群值

In [104]:
df.head()

,year,quarter,realgdp,realcons,realinv,realgovt,realdpi,cpi,m1,tbilrate,unemp,pop,infl,realint,year_str
0,1959.0,1.0,2710.349,1707.4,286.898,470.045,1886.9,28.98,139.7,2.82,5.8,177.146,0.00,0.00,1959.0
1,1959.0,2.0,2778.801,1733.7,310.859,481.301,1919.7,29.15,141.7,3.08,5.1,177.830,2.34,0.74,1959.0
2,1959.0,3.0,2775.488,1751.8,289.226,491.260,1916.4,29.35,140.5,3.82,5.3,178.657,2.74,1.09,1959.0
3,1959.0,4.0,2785.204,1753.7,299.356,484.052,1931.3,29.37,140.0,4.33,5.6,179.386,0.27,4.06,1959.0
4,1960.0,1.0,2847.699,1770.5,331.722,462.199,1955.5,29.54,139.6,3.50,5.2,180.007,2.31,1.19,1960.0

In [105]:
df['year'].astype('int')
df1=df['year'].astype('int')
df1.head()

0    1959
1    1959
2    1959
3    1959
4    1960
Name: year, dtype: int32

In [106]:
df['year'].astype('int')

0      1959
1      1959
2      1959
3      1959
4      1960
5      1960
6      1960
7      1960
8      1961
9      1961
10     1961
11     1961
12     1962
13     1962
14     1962
15     1962
16     1963
17     1963
18     1963
19     1963
20     1964
21     1964
22     1964
23     1964
24     1965
25     1965
26     1965
27     1965
28     1966
29     1966
       ...
173    2002
174    2002
175    2002
176    2003
177    2003
178    2003
179    2003
180    2004
181    2004
182    2004
183    2004
184    2005
185    2005
186    2005
187    2005
188    2006
189    2006
190    2006
191    2006
192    2007
193    2007
194    2007
195    2007
196    2008
197    2008
198    2008
199    2008
200    2009
201    2009
202    2009
Name: year, Length: 203, dtype: int32

In [161]:
df['year_str']=df['year'].astype('str')

df.dtypes
df.describe(include='all').T
df['year_str'].max()

'2009.0'

In [15]:
df['year_str'].value_counts()

1984.0    4
1971.0    4
1981.0    4
1980.0    4
1979.0    4
1978.0    4
1977.0    4
1976.0    4
1975.0    4
1974.0    4
1973.0    4
1972.0    4
1970.0    4
1983.0    4
1969.0    4
1968.0    4
1967.0    4
1966.0    4
1965.0    4
1964.0    4
1963.0    4
1962.0    4
1961.0    4
1960.0    4
1982.0    4
1959.0    4
2008.0    4
1997.0    4
2007.0    4
2006.0    4
2005.0    4
2004.0    4
2003.0    4
2002.0    4
2001.0    4
2000.0    4
1999.0    4
1998.0    4
1996.0    4
1985.0    4
1995.0    4
1994.0    4
1993.0    4
1992.0    4
1991.0    4
1990.0    4
1989.0    4
1988.0    4
1987.0    4
1986.0    4
2009.0    3
Name: year_str, dtype: int64

In [148]:
df['year'].value_counts().shape

(51,)

In [221]:
type(df['year'].value_counts())

pandas.core.series.Series

In [108]:
a=pd.DataFrame(df['year'].value_counts())
#a
a.reset_index(inplace=True)
a
#b=a.reset_index(inplace=False)
#print(a)
#print(b)
#a.shape
#a

     index  year
0   2007.0     4
1   1992.0     4
2   1979.0     4
3   1973.0     4
4   1967.0     4
5   1961.0     4
6   2008.0     4
7   2004.0     4
8   2003.0     4
9   2000.0     4
10  1998.0     4
11  1996.0     4
12  1988.0     4
13  1991.0     4
14  1986.0     4
15  1984.0     4
16  1981.0     4
17  1980.0     4
18  1976.0     4
19  1972.0     4
20  1970.0     4
21  1968.0     4
22  1964.0     4
23  1960.0     4
24  1985.0     4
25  1993.0     4
26  2001.0     4
27  1999.0     4
28  1995.0     4
29  1989.0     4
30  1983.0     4
31  1977.0     4
32  1971.0     4
33  1969.0     4
34  1963.0     4
35  2006.0     4
36  2002.0     4
37  1997.0     4
38  1994.0     4
39  1990.0     4
40  1987.0     4
41  1982.0     4
42  1978.0     4
43  1975.0     4
44  1974.0     4
45  1966.0     4
46  1965.0     4
47  1962.0     4
48  2005.0     4
49  1959.0     4
50  2009.0     3

In [16]:
df = pd.read_excel('data/bonus_schedule.xls')
df.describe(include='all').T
#df.Employed_Before.value_counts()

<ipython-input-16-de60823f10a6>:2: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  df.describe(include='all').T
<ipython-input-16-de60823f10a6>:2: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  df.describe(include='all').T

,count,unique,top,freq,first,last,mean,std,min,25%,50%,75%,max
Employed_After,5,5,1999-01-01 00:00:00,1,1974-01-01,2008-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Employed_Before,5,5,1988-12-31 00:00:00,1,1980-12-31,2008-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bonus_Percent,5,NaN,NaN,NaN,NaT,NaT,0.0148,0.00707637,0.005,0.01,0.0175,0.0195,0.022
diff,5,NaN,NaN,NaN,NaT,NaT,7.00219,3.5367,1,7.00274,8.00274,9.00274,10.0027
note,1,1,"fdsfsdf,fdsf",1,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df.Employed_Before.unique()

array(['1980-12-31T00:00:00.000000000', '1988-12-31T00:00:00.000000000',
       '1998-12-31T00:00:00.000000000', '2007-12-31T00:00:00.000000000',
       '2008-12-31T00:00:00.000000000'], dtype='datetime64[ns]')

In [23]:
df.dtypes

Employed_After     datetime64[ns]
Employed_Before    datetime64[ns]
Bonus_Percent             float64
diff                      float64
note                       object
dtype: object

In [24]:
#df.describe(include='all').T
df

  Employed_After  Employed_Before  Bonus_Percent      diff          note
0      1974-01-01      1980-12-31         0.0220   7.00274  fdsfsdf,fdsf
1      1981-01-01      1988-12-31         0.0195   8.00274           NaN
2      1989-01-01      1998-12-31         0.0175  10.00274           NaN
3      1999-01-01      2007-12-31         0.0100   9.00274           NaN
4      2008-01-01      2008-12-31         0.0050   1.00000           NaN

In [115]:
df[df.Bonus_Percent<0.02]

  Employed_After  Employed_Before  Bonus_Percent      diff note
1      1981-01-01      1988-12-31         0.0195   8.00274  NaN
2      1989-01-01      1998-12-31         0.0175  10.00274  NaN
3      1999-01-01      2007-12-31         0.0100   9.00274  NaN
4      2008-01-01      2008-12-31         0.0050   1.00000  NaN

In [25]:
df[(df.Bonus_Percent<0.02) & (df['diff']>8 )]['Employed_Before']

1   1988-12-31
2   1998-12-31
3   2007-12-31
Name: Employed_Before, dtype: datetime64[ns]

In [150]:
(df.Bonus_Percent<0.02) & (df['diff']>8 )

0    False
1     True
2     True
3     True
4    False
dtype: bool

In [26]:
df['diff'][(df.Bonus_Percent<0.02) & (df['diff']>8 )]

1     8.00274
2    10.00274
3     9.00274
Name: diff, dtype: float64

In [27]:
df[df.Bonus_Percent<0.02][['Bonus_Percent','diff']]

   Bonus_Percent      diff
1         0.0195   8.00274
2         0.0175  10.00274
3         0.0100   9.00274
4         0.0050   1.00000

In [29]:
from datetime import datetime
s="28-01-2011"
str(s) 
datetime.strptime(s, '%d-%m-%Y')

num = datetime.strptime(s, "%d-%m-%Y").day
num

28

In [297]:
df

  Employed_After  Employed_Before  Bonus_Percent      diff          note
0      1974-01-01      1980-12-31         0.0220   7.00274  fdsfsdf,fdsf
1      1981-01-01      1988-12-31         0.0195   8.00274           NaN
2      1989-01-01      1998-12-31         0.0175  10.00274           NaN
3      1999-01-01      2007-12-31         0.0100   9.00274           NaN
4      2008-01-01      2008-12-31         0.0050   1.00000           NaN

In [35]:
#datetime.strptime(str(df['Employed_Before'].values[1])[2:11], '%Y-%m-%d').year
datetime.strptime(str(df['Employed_Before'][3])[0:9],'%Y-%m-%d').year

int

In [34]:
str(df['Employed_Before'][3])[0:4]

'2007'

In [288]:
str(df['Employed_Before'].values[1])

'1988-12-31T00:00:00.000000000'

In [ ]:
datetime.strptime(str(x)[2:11], '%Y-%m-%d').year

In [60]:
?datetime.strptime

sort_index可以以轴的标签进行排序。axis是指用于排序的轴，可选的值有0和1，默认为0即行标签（Y轴），1为按照列标签排序。 ascending是排序方式，默认为True即降序排列

In [117]:
print (df)

print (df.sort_index(axis=0, ascending=False))
#print (df.sort_index(axis=1, ascending=False))

  Employed_After  Employed_Before  Bonus_Percent      diff          note
0      1974-01-01      1980-12-31         0.0220   7.00274  fdsfsdf,fdsf
1      1981-01-01      1988-12-31         0.0195   8.00274           NaN
2      1989-01-01      1998-12-31         0.0175  10.00274           NaN
3      1999-01-01      2007-12-31         0.0100   9.00274           NaN
4      2008-01-01      2008-12-31         0.0050   1.00000           NaN
  Employed_After  Employed_Before  Bonus_Percent      diff          note
4      2008-01-01      2008-12-31         0.0050   1.00000           NaN
3      1999-01-01      2007-12-31         0.0100   9.00274           NaN
2      1989-01-01      1998-12-31         0.0175  10.00274           NaN
1      1981-01-01      1988-12-31         0.0195   8.00274           NaN
0      1974-01-01      1980-12-31         0.0220   7.00274  fdsfsdf,fdsf

In [197]:

print (df.sort_values(by='diff'))

print (df.sort_values(by=['Bonus_Percent','diff'],ascending=[0,1]))
df

  Employed_After  Employed_Before  Bonus_Percent      diff          note
4      2008-01-01      2008-12-31         0.0050   1.00000           NaN
0      1974-01-01      1980-12-31         0.0220   7.00274  fdsfsdf,fdsf
1      1981-01-01      1988-12-31         0.0195   8.00274           NaN
3      1999-01-01      2007-12-31         0.0100   9.00274           NaN
2      1989-01-01      1998-12-31         0.0175  10.00274           NaN
  Employed_After  Employed_Before  Bonus_Percent      diff          note
0      1974-01-01      1980-12-31         0.0220   7.00274  fdsfsdf,fdsf
1      1981-01-01      1988-12-31         0.0195   8.00274           NaN
2      1989-01-01      1998-12-31         0.0175  10.00274           NaN
3      1999-01-01      2007-12-31         0.0100   9.00274           NaN
4      2008-01-01      2008-12-31         0.0050   1.00000           NaN

DataFrame也提供按照指定列进行排序，可以仅指定一个列作为排序标准（以单独列名作为columns的参数），也可以进行多重排序（columns的参数为一个列名的List，列名的出现顺序决定排序中的优先级），在多重排序中ascending参数也为一个List，分别与columns中的List元素对应

In [306]:
df = pd.read_excel('data/test11.xls', 'Sheet1', index_col=0)
df

    child  parent
id
1      10      30
2      11      31
3      12      32
4      13      33
5      14      34
6      15      35
7      16      36
8      17      37
9      18      38
10     19      39
11     20      40

要查看Series或DataFrame对象的小样本，使用head()和tail()方法。默认要显示的元素数为5，但可以传递自定义数字。

In [85]:
pd.read_csv?

### 读取Excel文件

### 读取数据库数据

In [132]:
"""
import sqlite3
import mysql.connector
import sqlalchemy
"""

'\nimport sqlite3\nimport mysql.connector\nimport sqlalchemy\n'

In [88]:
mysql_engine = sqlalchemy.create_engine('mysql+mysqlconnector://root:1234@localhost/world', encoding='utf-8')
sql_table = pd.read_sql('show tables', mysql_engine)

In [89]:
sql_table

   Tables_in_world
0             city
1          country
2  countrylanguage

In [90]:
sqlite_engine = sqlalchemy.create_engine('sqlite:////WorkSpace/Data/SinaNews.db', encoding='utf-8')
sina_news = pd.read_sql("SELECT * FROM sinanewslink LIMIT 100", sqlite_engine)

In [131]:
#sina_news.tail(10)

### 数据输出

In [124]:
df.to_csv("data/test.csv", encoding="utf-8")

In [125]:
df.to_excel("data/test.xlsx", "lookatme")

In [1]:
#sqlite_engine_test = sqlalchemy.create_engi pd.date_range('1/1/2000', periods=8)ne('sqlite:////WorkSpace/Data/TestDB.db', encoding='utf-8')
#df.to_sql("dftest", sqlite_engine_test)

In [ ]:
pd.read_sql("SELECT * FROM dftest", sqlite_engine_test, index_col="index").head(7)

## 数据选取&描述

### 查看数据

Pandas对象有很多可以访问原数据的属性

In [65]:
index = pd.date_range('1/1/2000', periods=8)
df = pd.DataFrame(np.random.randn(8, 3), index=index, columns=list('ABC'))
df

                   A         B         C
2000-01-01  0.331388 -0.099772 -0.678699
2000-01-02 -0.887177  1.854339  0.538201
2000-01-03 -0.295554 -0.876505  1.125262
2000-01-04  0.064216 -1.052859 -0.204577
2000-01-05  1.141789  0.948445  0.536815
2000-01-06 -0.252301  0.715699  1.223410
2000-01-07  0.663263  1.432285  0.303005
2000-01-08 -0.437744 -1.180903  0.250104

In [66]:
df.shape

(8, 3)

In [67]:
df.index

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08'],
              dtype='datetime64[ns]', freq='D')

In [68]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [69]:
df.values

array([[ 0.33138789, -0.09977167, -0.67869885],
       [-0.88717724,  1.85433859,  0.5382009 ],
       [-0.29555371, -0.87650478,  1.12526183],
       [ 0.06421595, -1.05285875, -0.2045769 ],
       [ 1.14178948,  0.94844509,  0.53681512],
       [-0.25230088,  0.71569929,  1.22341031],
       [ 0.66326317,  1.43228528,  0.30300514],
       [-0.43774416, -1.18090298,  0.2501038 ]])

In [70]:
df.head()

                   A         B         C
2000-01-01  0.331388 -0.099772 -0.678699
2000-01-02 -0.887177  1.854339  0.538201
2000-01-03 -0.295554 -0.876505  1.125262
2000-01-04  0.064216 -1.052859 -0.204577
2000-01-05  1.141789  0.948445  0.536815

In [71]:
df.tail(3)

                   A         B         C
2000-01-06 -0.252301  0.715699  1.223410
2000-01-07  0.663263  1.432285  0.303005
2000-01-08 -0.437744 -1.180903  0.250104

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 8 entries, 2000-01-01 to 2000-01-08
Freq: D
Data columns (total 3 columns):
A    8 non-null float64
B    8 non-null float64
C    8 non-null float64
dtypes: float64(3)
memory usage: 256.0 bytes

In [73]:
df.describe(percentiles=[*np.arange(0.2,1,0.2)])

              A         B         C
count  8.000000  8.000000  8.000000
mean   0.040985  0.217591  0.386690
std    0.651790  1.183474  0.632613
min   -0.887177 -1.180903 -0.678699
20%   -0.380868 -0.982317 -0.022705
40%   -0.260951 -0.255118  0.292425
50%   -0.094042  0.307964  0.419910
60.0%  0.117650  0.762248  0.537092
80%    0.530513  1.238749  0.890437
max    1.141789  1.854339  1.223410

In [74]:
df.T

,2000-01-01 00:00:00,2000-01-02 00:00:00,2000-01-03 00:00:00,2000-01-04 00:00:00,2000-01-05 00:00:00,2000-01-06 00:00:00,2000-01-07 00:00:00,2000-01-08 00:00:00
A,0.331388,-0.887177,-0.295554,0.064216,1.141789,-0.252301,0.663263,-0.437744
B,-0.099772,1.854339,-0.876505,-1.052859,0.948445,0.715699,1.432285,-1.180903
C,-0.678699,0.538201,1.125262,-0.204577,0.536815,1.223410,0.303005,0.250104

In [75]:
df.sort_index(axis=1, ascending=False)

                   C         B         A
2000-01-01 -0.678699 -0.099772  0.331388
2000-01-02  0.538201  1.854339 -0.887177
2000-01-03  1.125262 -0.876505 -0.295554
2000-01-04 -0.204577 -1.052859  0.064216
2000-01-05  0.536815  0.948445  1.141789
2000-01-06  1.223410  0.715699 -0.252301
2000-01-07  0.303005  1.432285  0.663263
2000-01-08  0.250104 -1.180903 -0.437744

In [76]:
df.sort_values(by='B')

                   A         B         C
2000-01-08 -0.437744 -1.180903  0.250104
2000-01-04  0.064216 -1.052859 -0.204577
2000-01-03 -0.295554 -0.876505  1.125262
2000-01-01  0.331388 -0.099772 -0.678699
2000-01-06 -0.252301  0.715699  1.223410
2000-01-05  1.141789  0.948445  0.536815
2000-01-07  0.663263  1.432285  0.303005
2000-01-02 -0.887177  1.854339  0.538201

注意：排序默认的都是返回一个新的对象。如果需要修改原数据，那么需要传入参数 inplace=True.

### 选择&查询

在进行数据的选取查询时需要注意获取到的是一个复制还是一个视图

获取列

In [170]:
df = pd.DataFrame({'one' : pd.Series(np.random.randn(3), index=['a', 'b', 'c']),
                   'two' : pd.Series(np.random.randn(4), index=['a', 'b', 'c', 'd']),
                   'three' : pd.Series(np.random.randn(3), index=['b', 'c','d'])})
df

        one     three       two
a -2.357152       NaN  0.262455
b  0.522861  0.314355 -0.705939
c -1.046797 -1.048832  0.757750
d       NaN  0.259480  0.263729

In [171]:
df.one

a   -2.357152
b    0.522861
c   -1.046797
d         NaN
Name: one, dtype: float64

In [79]:
df["two"]

a   -0.719057
b   -0.188124
c    1.262715
d    0.686226
Name: two, dtype: float64

获取行

In [172]:
df[1:3]

        one     three       two
b  0.522861  0.314355 -0.705939
c -1.046797 -1.048832  0.757750

In [173]:
df["a":"c"]

        one     three       two
a -2.357152       NaN  0.262455
b  0.522861  0.314355 -0.705939
c -1.046797 -1.048832  0.757750

In [174]:
df['four'] = ['A', 'A','B','C']
df

        one     three       two four
a -2.357152       NaN  0.262455    A
b  0.522861  0.314355 -0.705939    A
c -1.046797 -1.048832  0.757750    B
d       NaN  0.259480  0.263729    C

In [84]:
df[df['four'].isin(['A','C'])]

        one     three       two four
a  1.359970       NaN -0.719057    A
b -1.980051 -0.450368 -0.188124    A
d       NaN -0.568053  0.686226    C

### 基于标签的索引

.loc是基于标签的索引，必须使用数据的标签属性，否则会返回一个异常

Object Type | Indexers
-|-
Series | s.loc[indexer]
DataFrame | df.loc[row_indexer,column_indexer]

In [175]:
df2 = pd.DataFrame(np.random.randn(6,4),
                   index=list('abcdef'),
                   columns=list('ABCD'))
df2

          A         B         C         D
a  0.968639 -0.795396 -0.127285 -0.344673
b  0.158065  0.514720  0.694857  0.165280
c  0.097114 -1.376121  1.426877 -0.019839
d -0.360443  0.451347 -1.978543 -1.583470
e -0.682510  0.880194 -0.596178  1.650624
f -0.319746 -0.370895  0.988959 -0.603365

In [86]:
df2.loc['b':'d']

          A         B         C         D
b  1.374075 -0.362727  1.371830  1.347415
c  0.937339 -0.668834  1.969570 -0.546170
d  0.626059  1.111958 -0.142387 -0.602875

注意：基于标签的索引切片会包含首尾的两个索引

In [87]:
df2.loc['a']

A   -0.148745
B    0.313618
C    1.047956
D    2.338404
Name: a, dtype: float64

可以传入单个字符串或数字索引到某行或列，但注意即使传入的是数值表示的也是数值的标签，而非位置。

In [88]:
df2.loc[['a', 'b', 'd'], :]

          A         B         C         D
a -0.148745  0.313618  1.047956  2.338404
b  1.374075 -0.362727  1.371830  1.347415
d  0.626059  1.111958 -0.142387 -0.602875

In [89]:
df2.loc['d':, 'A':'C']

          A         B         C
d  0.626059  1.111958 -0.142387
e  0.500808 -1.191032  0.027550
f -0.602862  1.415485 -0.044950

In [90]:
df2.loc[:, df2.loc['a'] > 0]

          B         C         D
a  0.313618  1.047956  2.338404
b -0.362727  1.371830  1.347415
c -0.668834  1.969570 -0.546170
d  1.111958 -0.142387 -0.602875
e -1.191032  0.027550  0.456379
f  1.415485 -0.044950  1.345577

In [91]:
df2.loc['d','B']

1.1119582840735782

In [92]:
df2.at['d','B']

1.1119582840735782

.loc同时也可以用来扩展。

In [176]:
df2

          A         B         C         D
a  0.968639 -0.795396 -0.127285 -0.344673
b  0.158065  0.514720  0.694857  0.165280
c  0.097114 -1.376121  1.426877 -0.019839
d -0.360443  0.451347 -1.978543 -1.583470
e -0.682510  0.880194 -0.596178  1.650624
f -0.319746 -0.370895  0.988959 -0.603365

In [93]:
df2.loc[:,"E"] = df2.loc[:,"A"].apply(abs)
df2

          A         B         C         D         E
a -0.148745  0.313618  1.047956  2.338404  0.148745
b  1.374075 -0.362727  1.371830  1.347415  1.374075
c  0.937339 -0.668834  1.969570 -0.546170  0.937339
d  0.626059  1.111958 -0.142387 -0.602875  0.626059
e  0.500808 -1.191032  0.027550  0.456379  0.500808
f -0.602862  1.415485 -0.044950  1.345577  0.602862

In [177]:
df2.loc["g"] = 8.88
df2

          A         B         C         D
a  0.968639 -0.795396 -0.127285 -0.344673
b  0.158065  0.514720  0.694857  0.165280
c  0.097114 -1.376121  1.426877 -0.019839
d -0.360443  0.451347 -1.978543 -1.583470
e -0.682510  0.880194 -0.596178  1.650624
f -0.319746 -0.370895  0.988959 -0.603365
g  8.880000  8.880000  8.880000  8.880000

Series也可以使用.loc操作

In [178]:
ser = df2.B
ser

a   -0.795396
b    0.514720
c   -1.376121
d    0.451347
e    0.880194
f   -0.370895
g    8.880000
Name: B, dtype: float64

In [179]:
ser.loc['c':]

c   -1.376121
d    0.451347
e    0.880194
f   -0.370895
g    8.880000
Name: B, dtype: float64

In [180]:
ser.loc['e']

0.88019438413054363

### 基于位置的索引

.iloc是基于位置的索引，传入的参数为目标区域的位置索引。

In [181]:
ser2 = pd.Series(np.random.randn(5), index=list(range(0,10,2)))

In [182]:
ser2

0    1.814360
2    0.641015
4   -0.158165
6    1.766630
8    1.046369
dtype: float64

In [183]:
ser.iloc[:3]

a   -0.795396
b    0.514720
c   -1.376121
Name: B, dtype: float64

In [ ]:
ser.iloc[3]

In [ ]:
ser.iloc[:3] = 0
ser

In [ ]:
df4 = pd.DataFrame(np.random.randn(6,4),
                   index=list(range(0,12,2)),
                   columns=list(range(0,8,2)))
df4

In [ ]:
df4.iloc[:3]

In [ ]:
df4.iloc[1:5, 2:4]

In [ ]:
df4.iloc[[1, 3, 5], [1, 3]]

In [ ]:
df4.iloc[1:3, :]

In [ ]:
df4.iloc[:, 1:3]

In [ ]:
df4.iloc[1, 1]

In [ ]:
df4.iat[1,1]

注意：单个值（标量）索引方式 .at 和 .iat 在效率和低开销上比.loc和.iloc都要优秀很多。

In [ ]:
df4.iloc[1]

使用函数作为参数

In [98]:
df5 = pd.DataFrame(np.random.randn(6, 4),
                   index=list('abcdef'),
                   columns=list('ABCD'))
df5

          A         B         C         D
a -0.555727 -0.104842 -2.243208  0.021647
b  0.466586  1.920189 -0.352508 -0.371512
c  0.044623 -0.303453 -1.734542  1.575109
d -1.069629  1.758877  0.890070 -0.869682
e  0.708929 -0.045938 -0.843343  0.658547
f  1.030314  1.393514  0.585039 -0.477314

In [99]:
df5.loc[lambda df: df.A > 0, :]

          A         B         C         D
b  0.466586  1.920189 -0.352508 -0.371512
c  0.044623 -0.303453 -1.734542  1.575109
e  0.708929 -0.045938 -0.843343  0.658547
f  1.030314  1.393514  0.585039 -0.477314

In [100]:
df5.loc[:, lambda df: ['A', 'B']]

          A         B
a -0.555727 -0.104842
b  0.466586  1.920189
c  0.044623 -0.303453
d -1.069629  1.758877
e  0.708929 -0.045938
f  1.030314  1.393514

In [101]:
df5.iloc[:, lambda df: [0, 1]]

          A         B
a -0.555727 -0.104842
b  0.466586  1.920189
c  0.044623 -0.303453
d -1.069629  1.758877
e  0.708929 -0.045938
f  1.030314  1.393514

In [102]:
df5[lambda df: df.columns[0]]

a   -0.555727
b    0.466586
c    0.044623
d   -1.069629
e    0.708929
f    1.030314
Name: A, dtype: float64

In [103]:
df5.A.loc[lambda s: s > 0]

b    0.466586
c    0.044623
e    0.708929
f    1.030314
Name: A, dtype: float64

In [106]:
df5.loc[lambda s: s.A+s.B>0,:]

          A         B         C         D
b  0.466586  1.920189 -0.352508 -0.371512
d -1.069629  1.758877  0.890070 -0.869682
e  0.708929 -0.045938 -0.843343  0.658547
f  1.030314  1.393514  0.585039 -0.477314

In [114]:
df5

          A         B         C         D
a -0.555727 -0.104842 -2.243208  0.021647
b  0.466586  1.920189 -0.352508 -0.371512
c  0.044623 -0.303453 -1.734542  1.575109
d -1.069629  1.758877  0.890070 -0.869682
e  0.708929 -0.045938 -0.843343  0.658547
f  1.030314  1.393514  0.585039 -0.477314

In [137]:
np.sum(df5.values,axis=1)

array([-2.88212878,  1.66275522, -0.4182629 ,  0.70963568,  0.47819428,
        2.53155323])

In [121]:
?df.sum()

In [130]:
df5

          A         B         C         D
a -0.555727 -0.104842 -2.243208  0.021647
b  0.466586  1.920189 -0.352508 -0.371512
c  0.044623 -0.303453 -1.734542  1.575109
d -1.069629  1.758877  0.890070 -0.869682
e  0.708929 -0.045938 -0.843343  0.658547
f  1.030314  1.393514  0.585039 -0.477314

In [135]:
#df5.loc[lambda s: s.sum(axis=1)>0,:]
df5.loc[:,lambda s: s.sum(axis=0)>0]

          A         B         D
a -0.555727 -0.104842  0.021647
b  0.466586  1.920189 -0.371512
c  0.044623 -0.303453  1.575109
d -1.069629  1.758877 -0.869682
e  0.708929 -0.045938  0.658547
f  1.030314  1.393514 -0.477314

### *混合索引

警告：从Pandas 0.20.0开始，.ix索引（混合索引）已被弃用，推荐使用更严格的.iloc和.loc索引器。

原有的的混合索引方式

```
df.ix[[0, 2], 'A']
```

可以用下面的两种方式进行替代：

```
df.loc[df.index[[0, 2]], 'A']

df.iloc[[0, 2], df.columns.get_loc('A')]
```

如果是多个索引，可以使用 .get_indexer
```
df.iloc[[0, 2], df.columns.get_indexer(['A', 'B'])]
```

### 布尔型索引

另一个常见的操作是使用布尔向量来过滤选取数据。 
```
 | 代表 or, & 代表 and,  ~ 代表 not  
其中表示not的也有使用 - 的，但是建议使用 ~
```
这些运算必须使用括号分组。

In [ ]:
s = pd.Series(range(-3, 4))
s

In [ ]:
s[s > 0]

In [ ]:
s[(s < -1) | (s > 0.5)]

In [ ]:
s[~(s < 0)]

In [ ]:
s[-(s < 0)]

In [ ]:
df5

可以按照需要的条件筛选行

In [ ]:
df5[df5.A > 0]

结合列表推导式或map函数可以处理更复杂的选取逻辑

In [138]:
df6 = pd.DataFrame({'a' : ['one', 'one', 'two', 'three', 'two', 'one', 'six'],
                    'b' : ['x', 'y', 'y', 'x', 'y', 'x', 'x'],
                    'c' : np.random.randn(7)})
df6

       a  b         c
0    one  x  0.077324
1    one  y  2.356667
2    two  y -1.306177
3  three  x -0.491326
4    two  y  0.483075
5    one  x -0.372613
6    six  x  2.629625

获取A列值为 `'two' or 'three'`的数据

In [140]:
criterion = df6['a'].map(lambda x: x.startswith('t'))
criterion
#df6[criterion]

0    False
1    False
2     True
3     True
4     True
5    False
6    False
Name: a, dtype: bool

In [ ]:
df6[[x.startswith('t') for x in df6['a']]]

多重条件

In [ ]:
df6[criterion & (df6['b'] == 'x')]

组合使用

In [ ]:
df6.loc[criterion & (df6['b'] == 'x'),'b':'c']

和 `isin` 组合使用

In [ ]:
s = pd.Series(np.arange(5), index=np.arange(5)[::-1], dtype='int64')
s

In [ ]:
s.isin([2, 4, 6])

In [ ]:
s[s.isin([2, 4, 6])]

同样也可以应用在index对象上面。

In [ ]:
s[s.index.isin([2, 4, 6])]

注意和下面的区别

In [ ]:
s[[2, 4, 6]]

DataFrame也有一个isin方法，返回同样大小的矩阵。

In [ ]:
df = pd.DataFrame({'vals': [1, 2, 3, 4],
                   'ids': ['a', 'b', 'f', 'n'],
                   'ids2': ['a', 'n', 'c', 'n']})
df

In [ ]:
values = ['a', 'b', 1, 3]
df.isin(values)

当然，大多数情况下是对特定列的数据进行匹配的。

In [ ]:
values = {'ids': ['a', 'b'], 'vals': [1, 3]}
df.isin(values)

将DataFrame的isin与 any 和 all 方法结合，可以快速选择符合给定条件的数据子集。如：只选择每列都符合自己的标准的那些行：

In [ ]:
values = {'ids': ['a', 'b'], 'ids2': ['a', 'c'], 'vals': [1, 3]}
row_mask = df.isin(values).all(1)
df[row_mask]

In [ ]:
row_mask

通常我们返回的结果是原数据集的一个子集，使用where方法可以保证选择输出与原始数据的形状相同。

In [ ]:
s[s > 0]

In [ ]:
s.where(s > 0)

In [ ]:
df5[df5 < 0]

在返回的副本中，可使用其他参数替换条件为False的值。也可以通过inplace来修改原对象。

In [ ]:
df5.where(df5 < 0, other=-df5)

In [ ]:
df6 = df5.copy()

df6[df6 < 0] = 0

In [ ]:
df6

使用query()方法

In [ ]:
df = pd.DataFrame(np.random.rand(10, 3), columns=list('abc'))
df

In [ ]:
df[(df.a < df.b) & (df.b < df.c)]

In [ ]:
df.query('(a < b) & (b < c)')

这样的方法也可以应用到索引上

In [ ]:
df = pd.DataFrame(np.random.randint(10 / 2, size=(10, 2)), columns=list('bc'))
df.index.name = 'a'
df

In [ ]:
df.query('a < b and b < c')

如果索引没有被命名，也可以直接使用index表示索引。

In [ ]:
df.query('index < b < c')

注意：如果列名称和索引名称重复，那么列会被优先使用。

### 随机抽样

使用sample()方法可以从Series，DataFrame随机选择行或列。   
该方法将默认采样行，并接受指定数量的行/列返回。

In [ ]:
s = pd.Series([0,1,2,3,4,5])
s

默认抽样为一个

In [ ]:
s.sample()

In [ ]:
s.sample(n=3)

也可以指定返回百分比，但是不能与n同时使用。

In [ ]:
s.sample(frac=0.5)

默认情况下，一行样本最多返回一次，即为无放回抽样。但也可以使用replace选项替换抽样方式：

In [ ]:
s.sample(n=6, replace=False)

In [ ]:
s.sample(n=6, replace=True)

默认情况下，每一行被选择的概率相等。但是如果希望各行具有不同的概率，则可以提供权重作为sample方法的抽样权重。  
权重可以是列表，数字数组或Series，但长度必须与要采样的对象长度相同。

注意：如果权重之和不为1，那么函数会将所有权重除以权重之和来重新归一化。

In [ ]:
example_weights = [0, 0, 0.2, 0.2, 0.2, 0.4]
s.sample(n=3, weights=example_weights)

In [ ]:
example_weights2 = [0.5, 0, 0, 0, 0, 0]
s.sample(n=1, weights=example_weights2)

应用于DataFrame时，可以使用DataFrame的列作为采样权重（采样行而不是列的情况下），只需将列的名称作为字符串传递进去即可。

In [ ]:
df2 = pd.DataFrame({'col1':[9,8,7,6], 'weight_column':[0.5, 0.4, 0.1, 0]})
df2

In [ ]:
df2.sample(n = 3, weights = 'weight_column')

通过sample的axis参数可以对列进行采样

In [ ]:
df3 = pd.DataFrame({'col1':[1,2,3], 'col2':[2,3,4]})
df3

In [ ]:
df3.sample(n=1, axis=1)

如果需要重现随机结果，可以通过 random_state 参数设置随机数种子。

In [ ]:
df4 = pd.DataFrame({'col1':[1,2,3], 'col2':[2,3,4]})
df4

In [ ]:
df4.sample(n=2, random_state=2)

In [ ]:
df4.sample(n=2, random_state=2)

关于axis参数：
- 使用0值表示沿着每一列或行标签\索引值向下执行方法
- 使用1值表示沿着每一行或者列标签模向执行对应的方法

## 缺失值处理

Pandas中主要使用`np.nan`来表示缺失的数据。默认情况下不会被包括在计算中。

In [118]:
df = pd.DataFrame(np.random.randn(5, 3),
                  index=['a', 'c', 'e', 'f', 'h'],
                  columns=['one', 'two', 'three'])

df['four'] = 'bar'
df['five'] = df['one'] > 0

df

        one       two     three four   five
a -0.408040 -0.103925  1.567179  bar  False
c  0.497025  1.155872  1.838612  bar   True
e  1.535727  0.254998 -0.844157  bar   True
f -0.982943 -0.306098  0.838501  bar  False
h -1.690848  1.151174 -1.029337  bar  False

In [119]:
df2 = df.reindex(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])
df2

        one       two     three four   five
a -0.408040 -0.103925  1.567179  bar  False
b       NaN       NaN       NaN  NaN    NaN
c  0.497025  1.155872  1.838612  bar   True
d       NaN       NaN       NaN  NaN    NaN
e  1.535727  0.254998 -0.844157  bar   True
f -0.982943 -0.306098  0.838501  bar  False
g       NaN       NaN       NaN  NaN    NaN
h -1.690848  1.151174 -1.029337  bar  False

In [120]:
df3=df2.copy()
df3
print(id(df3))
id(df2)

438264440

438266176

In [121]:
df3.loc[df3["four"].isnull(),"four"]="bar"
df3

        one       two     three four   five
a -0.408040 -0.103925  1.567179  bar  False
b       NaN       NaN       NaN  bar    NaN
c  0.497025  1.155872  1.838612  bar   True
d       NaN       NaN       NaN  bar    NaN
e  1.535727  0.254998 -0.844157  bar   True
f -0.982943 -0.306098  0.838501  bar  False
g       NaN       NaN       NaN  bar    NaN
h -1.690848  1.151174 -1.029337  bar  False

In [126]:
df3.loc[df3["three"].isnull(),"three"]=df3["three"].median()

In [127]:
df3

        one       two     three four   five
a -0.408040 -0.103925  1.567179  bar  False
b       NaN       NaN  0.838501  bar    NaN
c  0.497025  1.155872  1.838612  bar   True
d       NaN       NaN  0.838501  bar    NaN
e  1.535727  0.254998 -0.844157  bar   True
f -0.982943 -0.306098  0.838501  bar  False
g       NaN       NaN  0.838501  bar    NaN
h -1.690848  1.151174 -1.029337  bar  False

为了使检测到的缺失值更容易（并且跨不同列和数据类型）。  
Pandas提供了isnull（）和notnull（）函数，它们也是Series和DataFrame对象的方法：

In [314]:
pd.isnull(df2['one'])

a    False
b     True
c    False
d     True
e    False
f    False
g     True
h    False
Name: one, dtype: bool

In [315]:
df2.isnull()

     one    two  three   four   five
a  False  False  False  False  False
b   True   True   True   True   True
c  False  False  False  False  False
d   True   True   True   True   True
e  False  False  False  False  False
f  False  False  False  False  False
g   True   True   True   True   True
h  False  False  False  False  False

需要注意的是在NumPy中np.nan之间是不同的。

In [146]:
None == None

True

In [147]:
np.nan == np.nan

False

In [148]:
type(np.nan)

float

因此，像下面的这样的条件判断是无效的。

In [156]:
df2['one'] == np.nan

a    False
b    False
c    False
d    False
e    False
f    False
g    False
h    False
Name: one, dtype: bool

### 插入缺失值

In [166]:
df3 = df[['one', 'two', 'three']].copy()
df3
df3.iloc[[0,1,-1],0] = np.nan

In [167]:
df3

        one       two     three
a       NaN  0.865548 -0.645044
c       NaN  0.369235 -0.462740
e  0.468042  0.552536 -0.337597
f -0.756776  1.216542  0.459939
h       NaN  0.779492 -0.442163

In [ ]:
df2 = df.copy()
df2['timestamp'] = pd.Timestamp('20120101')

In [ ]:
df2

In [ ]:
df2.loc[['a','c','h'],['one','timestamp']] = np.nan

In [ ]:
df2

In [ ]:
df2.get_dtype_counts()

### 缺失值的运算

- 当进行求和运算时，缺失的数据将会被当作零来计算。
- 如果数据全部为NA，那么结果也会返回NA。
- 像 cumsum 和 cumprod 等方法回忽略NA值，但是会在返回的结果数组中回显示缺失的值。

In [168]:
df3

        one       two     three
a       NaN  0.865548 -0.645044
c       NaN  0.369235 -0.462740
e  0.468042  0.552536 -0.337597
f -0.756776  1.216542  0.459939
h       NaN  0.779492 -0.442163

In [169]:
df3['one'].sum()

-0.28873351526353014

In [171]:
df3.mean(0)

one     -0.144367
two      0.756670
three   -0.285521
dtype: float64

In [172]:
df3.cumsum()

        one       two     three
a       NaN  0.865548 -0.645044
c       NaN  1.234782 -1.107784
e  0.468042  1.787318 -1.445381
f -0.288734  3.003860 -0.985441
h       NaN  3.783351 -1.427605

GroupBy中的NA值  
在GroupBy中NA值会被直接忽略，这点同R相同。

In [173]:
df3.groupby('one').mean()

                two     three
one
-0.756776  1.216542  0.459939
 0.468042  0.552536 -0.337597

有关详细信息，请参阅groupby部分。

### 清理/填补缺失数据

Pandas对象具有多种数据处理方法来处理缺失的数据。

fillna方法可以通过几种方式将非空数据填补到NA值的位置。

##### 使用标量填补

In [157]:
df2

        one       two     three four   five
a  0.182967  1.416209  1.516353  bar   True
b       NaN       NaN       NaN  NaN    NaN
c  0.074258  0.486881  0.056388  bar   True
d       NaN       NaN       NaN  NaN    NaN
e -1.081227  0.338767 -0.082341  bar  False
f  1.561056  0.459909 -1.505855  bar   True
g       NaN       NaN       NaN  NaN    NaN
h -1.864688 -0.480150 -1.493943  bar  False

In [158]:
df2.fillna(0)

        one       two     three four   five
a  0.182967  1.416209  1.516353  bar   True
b  0.000000  0.000000  0.000000    0      0
c  0.074258  0.486881  0.056388  bar   True
d  0.000000  0.000000  0.000000    0      0
e -1.081227  0.338767 -0.082341  bar  False
f  1.561056  0.459909 -1.505855  bar   True
g  0.000000  0.000000  0.000000    0      0
h -1.864688 -0.480150 -1.493943  bar  False

In [159]:
df2['four'].fillna('missing')

a        bar
b    missing
c        bar
d    missing
e        bar
f        bar
g    missing
h        bar
Name: four, dtype: object

##### 向前填充或向后填充

In [160]:
df2

        one       two     three four   five
a  0.182967  1.416209  1.516353  bar   True
b       NaN       NaN       NaN  NaN    NaN
c  0.074258  0.486881  0.056388  bar   True
d       NaN       NaN       NaN  NaN    NaN
e -1.081227  0.338767 -0.082341  bar  False
f  1.561056  0.459909 -1.505855  bar   True
g       NaN       NaN       NaN  NaN    NaN
h -1.864688 -0.480150 -1.493943  bar  False

In [182]:
df2.fillna(method='bfill',inplace=True)

In [180]:
?df2.fillna

In [ ]:
df2.fillna(method='bfill', limit=1)

其中填补的方式：
<table>
<colgroup>
<col width="38%">
<col width="63%">
</colgroup>
<thead valign="bottom">
<tr class="row-odd"><th class="head">Method</th>
<th class="head">Action</th>
</tr>
</thead>
<tbody valign="top">
<tr class="row-even"><td>pad / ffill</td>
<td>Fill values forward</td>
</tr>
<tr class="row-odd"><td>bfill / backfill</td>
<td>Fill values backward</td>
</tr>
</tbody>
</table>

##### 使用Pandas对象填充

也可以使用可对齐的dict或Series进行填充。Series的index 或 dict的标签必须与要填充的框架的列匹配。

In [ ]:
dff = pd.DataFrame(np.random.randn(10,3), columns=list('ABC'))
dff.iloc[3:5,0] = np.nan
dff.iloc[4:6,1] = np.nan
dff.iloc[5:8,2] = np.nan
dff

In [ ]:
dff.fillna(dff.mean())

In [ ]:
dff.fillna(dff.mean()['B':'C'])

In [ ]:
dff.where(pd.notnull(dff), dff.mean(), axis='columns')

### 删除缺失值

In [ ]:
df3["one"] = np.nan
df3

In [ ]:
df3.dropna(axis=0)

In [ ]:
df3.dropna(axis=1)

In [ ]:
df3['one'].dropna()

在删除缺失值时需要注意的是，DataFrame有两条轴，而Series只有一条，所以需要指定在哪条轴上操作。

### 插值

Series和Dataframe对象都具有插值方法，默认情况下，在缺少的数据点处执行线性插值。

In [ ]:
ser = pd.Series([0.469112, np.nan, 5.689738, np.nan, 8.916232])
ser

In [ ]:
ser.interpolate()

In [ ]:
df = pd.DataFrame({'A': [1, 2.1, np.nan, 4.7, 5.6, 6.8],
                   'B': [.25, np.nan, np.nan, 4, 12.2, 14.4]})

In [ ]:
df

In [ ]:
df.interpolate()

其中可以通过参数来控制插值的方式，不同的参数对应不同的差值方式和插值算法。详细内容见scipy。

- liner: 忽略索引对缺失部分进行等距的线性插值
- time: 在时间索引下，按日期或者更高的时间频率按等距进行插值。
- index, values: 使用索引的实际数值。
- 其他参数: 参见scipy内容。

In [ ]:
df.interpolate(method='index')

In [ ]:
df.interpolate(method='akima')

当通过多项式或样条近似进行插值时，还需要传入order参数。

In [ ]:
df.interpolate(method='polynomial', order=2)

同样可以通过limit参数来限制插值的个数。

In [ ]:
ser = pd.Series([np.nan, np.nan, 5, np.nan, np.nan, np.nan, 13])
ser

In [ ]:
ser.interpolate(limit=2)  # limit_direction == 'forward'

In [ ]:
ser.interpolate(limit=1, limit_direction='backward')

In [ ]:
ser.interpolate(limit=1, limit_direction='both')

### 替换

对于Series，可以通过另一个值替换单个值或多个值，也可以使用列表对应替换，或者使用字典指定替换多个值，也可以使用填补的方式来进行替换。

In [318]:
ser = pd.Series([0., 1., 2., 3., 4.])

ser.replace(0, 5)

0    5.0
1    1.0
2    2.0
3    3.0
4    4.0
dtype: float64

In [ ]:
ser.replace([0, 1, 2, 3, 4], [4, 3, 2, 1, 0])

In [ ]:
ser.replace({0: 10, 1: 100})

In [ ]:
ser.replace([1, 2, 3], method='pad')

对于数据框可以通过列来替换单个值

In [ ]:
df = pd.DataFrame({'a': [0, 1, 2, 3, 4], 'b': [5, 6, 7, 8, 9]})
df

In [ ]:
df.replace({'a': 0, 'b': 5}, 100)

字符串/正则表达式替换

In [ ]:
d = {'a': list(range(4)), 'b': list('ab..'), 'c': ['a', 'b', np.nan, 'd']}

df = pd.DataFrame(d)
df

字符串替换：

In [ ]:
df.replace('.', np.nan)

正则表达式替换

In [ ]:
df.replace(r'\s*\.\s*', np.nan, regex=True)

列表对应的字符串替换

In [ ]:
df.replace(['a', '.'], ['b', np.nan])

列表对应的正则表达式替换

In [ ]:
df.replace([r'\.', r'(a)'], ['dot', '\1stuff'], regex=True)

# 分组运算-GroupBy

通过使用GroupBy可以做到涉及一个或多个以下步骤的过程：

- 根据一些标准将数据拆分成组
- 独立应用功能给每个组
- 将结果合并成数据结构

## 将对象拆分成组

In [128]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar','foo', 'bar', 'foo', 'foo'],
                   'B' : ['one', 'one', 'two', 'three','two', 'two', 'one', 'three'],
                   'C' : np.random.randn(8),
                   'D' : np.random.randn(8)})

In [129]:
df

     A      B         C         D
0  foo    one -0.510992 -1.292794
1  bar    one -2.360271 -0.659920
2  foo    two  0.103595 -0.874005
3  bar  three  1.738818 -0.689551
4  foo    two  1.241876 -0.535480
5  bar    two  0.132413  1.527953
6  foo    one  0.577794  0.647206
7  foo  three -1.575906 -0.677337

可以使用一个或多个键执行GroupBy，键可以使用列或者行。

In [130]:
grouped = df.groupby('A')
#grouped = df.groupby(['A', 'B'])
#grouped.size()
grouped

In [192]:
def get_letter_type(letter):
    if letter.lower() in 'aeiou':
        return 'vowel'
    else:
        return 'consonant'


grouped = df.groupby(get_letter_type, axis=1)

In [131]:
grouped.groups

{'bar': Int64Index([1, 3, 5], dtype='int64'),
 'foo': Int64Index([0, 2, 4, 6, 7], dtype='int64')}

In [132]:
grouped.mean()

            C         D
A
bar -0.163013  0.059494
foo -0.032727 -0.546482

默认情况下，在groupby操作期间会进行排序。可以通过sort = False来进行潜在的加速：

In [ ]:
df3 = pd.DataFrame({'X' : ['A', 'B', 'A', 'B'], 'Y' : [1, 4, 3, 2]})
df3

In [ ]:
df3.groupby(['X']).get_group('A')

In [ ]:
df3.groupby(['X']).get_group('B')

## GroupBy对象属性

In [ ]:
df.groupby('A').groups

In [ ]:
grouped = df.groupby(['A', 'B'])
grouped.groups

查看分组个数

In [ ]:
len(grouped)

一旦创建了GroupBy对象，有几种方法可用于对分组数据执行计算

In [ ]:
grouped = df.groupby('A')
grouped.aggregate(np.sum)

In [ ]:
grouped = df.groupby(['A', 'B'])
grouped.aggregate(np.sum)

默认键值会被作为新的多层的索引，可以使用as_index=False来控制作为列输出，或者在生成的对象上使用reset_index()

In [ ]:
grouped.size() #查看分组大小

同时应用多个函数

In [ ]:
grouped = df.groupby('A')

In [ ]:
grouped['C'].agg([np.sum, np.mean, np.std])

在DataFrame的分组上，传递一个应用于每个列的函数列表，该列产生具有分层索引的聚合结果：

In [ ]:
grouped.agg([np.sum, np.mean, np.std])

如果需要对生成的列重新命名

In [ ]:
grouped['C'].agg([np.sum, np.mean, np.std]).rename(columns={'sum': 'foo',
                                                            'mean': 'bar',
                                                            'std': 'baz'})

In [ ]:
grouped.agg([np.sum, np.mean, np.std]).rename(columns={'sum': 'foo','mean': 'bar','std': 'baz'})

对不同的列使用不同的函数

In [ ]:
grouped.agg({'C' : np.sum,
             'D' : lambda x: np.std(x, ddof=1)})

# 补充

In [199]:
uefaDF=pd.read_csv('data/euro_winners.csv')
uefaDF.head()

,Season,Nation,Winners,Score,Runners-up,Runner-UpNation,Venue,Attendance
0,1955–56,Spain,Real Madrid,4–3,Stade de Reims,France,"Parc des Princes,Paris",38239
1,1956–57,Spain,Real Madrid,2–0,Fiorentina,Italy,"Santiago Bernabéu Stadium, Madrid",124000
2,1957–58,Spain,Real Madrid,3–2,Milan,Italy,"Heysel Stadium,Brussels",67000
3,1958–59,Spain,Real Madrid,2–0,Stade de Reims,France,"Neckarstadion,Stuttgart",72000
4,1959–60,Spain,Real Madrid,7–3,Eintracht Frankfurt,Germany,"Hampden Park,Glasgow",127621

In [202]:
uefaDF.shape
uefaDF.describe(include="all")

,Season,Nation,Winners,Score,Runners-up,Runner-UpNation,Venue,Attendance
count,58,58,58,58,58,58,58,58.000000
unique,58,10,22,21,33,14,29,NaN
top,2007–08,Spain,Real Madrid,1–0,Bayern Munich,Italy,"Wembley Stadium,London",NaN
freq,1,13,9,15,5,14,7,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66460.482759
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19261.993554
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26732.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53086.500000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63700.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73497.500000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,127621.000000

In [205]:
uefaDF['Nation'].value_counts()

Spain          13
England        12
Italy          12
Germany         7
Netherlands     6
Portugal        4
Scotland        1
Yugoslavia      1
France          1
Romania         1
Name: Nation, dtype: int64

In [5]:
uefaDF['Nation'].value_counts().index

Index(['Spain', 'England', 'Italy', 'Germany', 'Netherlands', 'Portugal',
       'France', 'Yugoslavia', 'Romania', 'Scotland'],
      dtype='object')

In [ ]:
tuple(nationsGrp.groups)

In [6]:
nationindex=uefaDF['Nation'].value_counts().index
nationindex
int(len(nationindex))

10

In [7]:
name=uefaDF['Nation'].value_counts().index
results=[]
for i in range(len(name)):
    flag=uefaDF['Nation']==name[i]
    tmp=uefaDF.Attendance[flag].mean()
    results.append(tmp)
    
results

[73477.15384615384,
 66534.25,
 65761.25,
 67583.28571428571,
 67489.0,
 49635.5,
 64400.0,
 56000.0,
 70000.0,
 45000.0]

In [207]:
nationsGrp =uefaDF.groupby('Nation');
type(nationsGrp)

In [208]:
nationsGrp.groups

{'England': Int64Index([12, 21, 22, 23, 24, 25, 26, 28, 43, 49, 52, 56], dtype='int64'),
 'France': Int64Index([37], dtype='int64'),
 'Germany': Int64Index([18, 19, 20, 27, 41, 45, 57], dtype='int64'),
 'Italy': Int64Index([7, 8, 9, 13, 29, 33, 34, 38, 40, 47, 51, 54], dtype='int64'),
 'Netherlands': Int64Index([14, 15, 16, 17, 32, 39], dtype='int64'),
 'Portugal': Int64Index([5, 6, 31, 48], dtype='int64'),
 'Romania': Int64Index([30], dtype='int64'),
 'Scotland': Int64Index([11], dtype='int64'),
 'Spain': Int64Index([0, 1, 2, 3, 4, 10, 36, 42, 44, 46, 50, 53, 55], dtype='int64'),
 'Yugoslavia': Int64Index([35], dtype='int64')}

In [10]:
d=nationsGrp.groups
for key in d:
    value=d[key]
    print (value)
    #print uefaDF.iloc[x,].mean()

Int64Index([12, 21, 22, 23, 24, 25, 26, 28, 43, 49, 52, 56], dtype='int64')
Int64Index([37], dtype='int64')
Int64Index([18, 19, 20, 27, 41, 45, 57], dtype='int64')
Int64Index([7, 8, 9, 13, 29, 33, 34, 38, 40, 47, 51, 54], dtype='int64')
Int64Index([14, 15, 16, 17, 32, 39], dtype='int64')
Int64Index([5, 6, 31, 48], dtype='int64')
Int64Index([30], dtype='int64')
Int64Index([11], dtype='int64')
Int64Index([0, 1, 2, 3, 4, 10, 36, 42, 44, 46, 50, 53, 55], dtype='int64')
Int64Index([35], dtype='int64')

In [210]:
ddd=nationsGrp.groups
for key in ddd:
    v=ddd[key]
   # print (v,key)
    print (uefaDF.iloc[v,].mean())

Attendance    66534.25
dtype: float64
Attendance    64400.0
dtype: float64
Attendance    67583.285714
dtype: float64
Attendance    65761.25
dtype: float64
Attendance    67489.0
dtype: float64
Attendance    49635.5
dtype: float64
Attendance    70000.0
dtype: float64
Attendance    45000.0
dtype: float64
Attendance    73477.153846
dtype: float64
Attendance    56000.0
dtype: float64

In [12]:
ddd=nationsGrp.groups
ddd.keys()

dict_keys(['England', 'France', 'Germany', 'Italy', 'Netherlands', 'Portugal', 'Romania', 'Scotland', 'Spain', 'Yugoslavia'])

In [13]:
ddd=nationsGrp.groups
ddd.values()

dict_values([Int64Index([12, 21, 22, 23, 24, 25, 26, 28, 43, 49, 52, 56], dtype='int64'), Int64Index([37], dtype='int64'), Int64Index([18, 19, 20, 27, 41, 45, 57], dtype='int64'), Int64Index([7, 8, 9, 13, 29, 33, 34, 38, 40, 47, 51, 54], dtype='int64'), Int64Index([14, 15, 16, 17, 32, 39], dtype='int64'), Int64Index([5, 6, 31, 48], dtype='int64'), Int64Index([30], dtype='int64'), Int64Index([11], dtype='int64'), Int64Index([0, 1, 2, 3, 4, 10, 36, 42, 44, 46, 50, 53, 55], dtype='int64'), Int64Index([35], dtype='int64')])

In [211]:
nationsGrp.mean()

               Attendance
Nation
England      66534.250000
France       64400.000000
Germany      67583.285714
Italy        65761.250000
Netherlands  67489.000000
Portugal     49635.500000
Romania      70000.000000
Scotland     45000.000000
Spain        73477.153846
Yugoslavia   56000.000000

In [212]:
nationsGrp.size()

Nation
England        12
France          1
Germany         7
Italy          12
Netherlands     6
Portugal        4
Romania         1
Scotland        1
Spain          13
Yugoslavia      1
dtype: int64

In [213]:
nationWins=nationsGrp.size()
print (nationWins.sort_values(ascending=True,inplace=False))
#nationWins

Nation
France          1
Romania         1
Scotland        1
Yugoslavia      1
Portugal        4
Netherlands     6
Germany         7
England        12
Italy          12
Spain          13
dtype: int64

In [17]:
nationWins.sort_values(ascending=True,inplace=True)
nationWins

Nation
France          1
Romania         1
Scotland        1
Yugoslavia      1
Portugal        4
Netherlands     6
Germany         7
England        12
Italy          12
Spain          13
dtype: int64

In [223]:
uefaDF["num"]=uefaDF["Attendance"]*1.5

In [224]:
winnersGrp =uefaDF.groupby(['Nation','Winners'])
clubWins=winnersGrp.size()
clubWins
#clubWins.sort_values(ascending=False)
#clubWins

Nation       Winners
England      Aston Villa          1
             Chelsea              1
             Liverpool            5
             Manchester United    3
             Nottingham Forest    2
France       Marseille            1
Germany      Bayern Munich        5
             Borussia Dortmund    1
             Hamburg              1
Italy        Internazionale       3
             Juventus             2
             Milan                7
Netherlands  Ajax                 4
             Feyenoord            1
             PSV Eindhoven        1
Portugal     Benfica              2
             Porto                2
Romania      Steaua Bucure?ti     1
Scotland     Celtic               1
Spain        Barcelona            4
             Real Madrid          9
Yugoslavia   Red Star Belgrade    1
dtype: int64

In [228]:
winnersGrp.describe(include="all").T

Nation                             England                        \
Winners                        Aston Villa               Chelsea
Attendance      count                    1                     1
                unique                 NaN                   NaN
                top                    NaN                   NaN
                freq                   NaN                   NaN
                mean                 46000                 62500
                std                    NaN                   NaN
                min                  46000                 62500
                25%                  46000                 62500
                50%                  46000                 62500
                75%                  46000                 62500
                max                  46000                 62500
Runner-UpNation count                    1                     1
                unique                   1                     1
                top                Germany               Germany
                freq                     1                     1
                mean                   NaN                   NaN
                std                    NaN                   NaN
                min                    NaN                   NaN
                25%                    NaN                   NaN
                50%                    NaN                   NaN
                75%                    NaN                   NaN
                max                    NaN                   NaN
Runners-up      count                    1                     1
                unique                   1                     1
                top          Bayern Munich         Bayern Munich
                freq                     1                     1
                mean                   NaN                   NaN
                std                    NaN                   NaN
                min                    NaN                   NaN
                25%                    NaN                   NaN
...                                    ...                   ...
Season          freq                     1                     1
                mean                   NaN                   NaN
                std                    NaN                   NaN
                min                    NaN                   NaN
                25%                    NaN                   NaN
                50%                    NaN                   NaN
                75%                    NaN                   NaN
                max                    NaN                   NaN
Venue           count                    1                     1
                unique                   1                     1
                top     De Kuip, Rotterdam  Allianz Arena,Munich
                freq                     1                     1
                mean                   NaN                   NaN
                std                    NaN                   NaN
                min                    NaN                   NaN
                25%                    NaN                   NaN
                50%                    NaN                   NaN
                75%                    NaN                   NaN
                max                    NaN                   NaN
num             count                    1                     1
                unique                 NaN                   NaN
                top                    NaN                   NaN
                freq                   NaN                   NaN
                mean                 69000                 93750
                std                    NaN                   NaN
                min                  69000                 93750
                25%                  69000                 93750
                50%                  69000                 93750
                75%                  69000                 93750
                max                  69000                 93750

Nation                                                             \
Winners                            Liverpool    Manchester United
Attendance      count                      5                    3
                unique                   NaN                  NaN
                top                      NaN                  NaN
                freq                     NaN                  NaN
                mean                 66326.2                83260
                std                    17531              13848.5
                min                    48360                67310
                25%                    52078              78777.5
                50%                    69000                90245
                75%                    69693                91235
                max                    92500                92225
Runner-UpNation count                      5                    3
                unique                     4                    3
                top                    Italy              England
                freq                       2                    1
                mean                     NaN                  NaN
                std                      NaN                  NaN
                min                      NaN                  NaN
                25%                      NaN                  NaN
                50%                      NaN                  NaN
                75%                      NaN                  NaN
                max                      NaN                  NaN
Runners-up      count                      5                    3
                unique                     5                    3
                top                     Roma              Chelsea
                freq                       1                    1
                mean                     NaN                  NaN
                std                      NaN                  NaN
                min                      NaN                  NaN
                25%                      NaN                  NaN
...                                      ...                  ...
Season          freq                       1                    1
                mean                     NaN                  NaN
                std                      NaN                  NaN
                min                      NaN                  NaN
                25%                      NaN                  NaN
                50%                      NaN                  NaN
                75%                      NaN                  NaN
                max                      NaN                  NaN
Venue           count                      5                    3
                unique                     4                    3
                top     Stadio Olimpico,Rome  Camp Nou, Barcelona
                freq                       2                    1
                mean                     NaN                  NaN
                std                      NaN                  NaN
                min                      NaN                  NaN
                25%                      NaN                  NaN
                50%                      NaN                  NaN
                75%                      NaN                  NaN
                max                      NaN                  NaN
num             count                      5                    3
                unique                   NaN                  NaN
                top                      NaN                  NaN
                freq                     NaN                  NaN
                mean                 99489.3               124890
                std                  26296.5              20772.8
                min                    72540               100965
                25%                    78117               118166
                50%                   103500               135368
                75%                   104540               136852
                max                   138750               138338

Nation                                                     \
Winners                                 Nottingham Forest
Attendance      count                                   2
                unique                                NaN
                top                                   NaN
                freq                                  NaN
                mean                                54250
                std                               4596.19
                min                                 51000
                25%                                 52625
                50%                                 54250
                75%                                 55875
                max                                 57500
Runner-UpNation count                                   2
                unique                                  2
                top                                Sweden
                freq                                    1
                mean                                  NaN
                std                                   NaN
                min                                   NaN
                25%                                   NaN
                50%                                   NaN
                75%                                   NaN
                max                                   NaN
Runners-up      count                                   2
                unique                                  2
                top                              Malmö FF
                freq                                    1
                mean                                  NaN
                std                                   NaN
                min                                   NaN
                25%                                   NaN
...                                                   ...
Season          freq                                    1
                mean                                  NaN
                std                                   NaN
                min                                   NaN
                25%                                   NaN
                50%                                   NaN
                75%                                   NaN
                max                                   NaN
Venue           count                                   2
                unique                                  2
                top     Santiago Bernabéu Stadium, Madrid
                freq                                    1
                mean                                  NaN
                std                                   NaN
                min                                   NaN
                25%                                   NaN
                50%                                   NaN
                75%                                   NaN
                max                                   NaN
num             count                                   2
                unique                                NaN
                top                                   NaN
                freq                                  NaN
                mean                                81375
                std                               6894.29
                min                                 76500
                25%                               78937.5
                50%                                 81375
                75%                               83812.5
                max                                 86250

Nation                                 France                 Germany  \
Winners                             Marseille           Bayern Munich
Attendance      count                       1                       5
                unique                    NaN                     NaN
                top                       NaN                     NaN
                freq                      NaN                     NaN
                mean                    64400                 68116.6
                std                       NaN                 16045.7
                min                     64400                   48374
                25%                     64400                   54864
                50%                     64400                   72047
                75%                     64400                   79000
                max                     64400                   86298
Runner-UpNation count                       1                       5
                unique                      1                       4
                top                     Italy                   Spain
                freq                        1                       2
                mean                      NaN                     NaN
                std                       NaN                     NaN
                min                       NaN                     NaN
                25%                       NaN                     NaN
                50%                       NaN                     NaN
                75%                       NaN                     NaN
                max                       NaN                     NaN
Runners-up      count                       1                       5
                unique                      1                       5
                top                     Milan           Saint-Étienne
                freq                        1                       1
                mean                      NaN                     NaN
                std                       NaN                     NaN
                min                       NaN                     NaN
                25%                       NaN                     NaN
...                                       ...                     ...
Season          freq                        1                       1
                mean                      NaN                     NaN
                std                       NaN                     NaN
                min                       NaN                     NaN
                25%                       NaN                     NaN
                50%                       NaN                     NaN
                75%                       NaN                     NaN
                max                       NaN                     NaN
Venue           count                       1                       5
                unique                      1                       5
                top     Olympiastadion,Munich  Wembley Stadium,London
                freq                        1                       1
                mean                      NaN                     NaN
                std                       NaN                     NaN
                min                       NaN                     NaN
                25%                       NaN                     NaN
                50%                       NaN                     NaN
                75%                       NaN                     NaN
                max                       NaN                     NaN
num             count                       1                       5
                unique                    NaN                     NaN
                top                       NaN                     NaN
                freq                      NaN                     NaN
                mean                    96600                  102175
                std                       NaN                 24068.6
                min                     96600                   72561
                25%                     96600                   82296
                50%                     96600                  108070
                75%                     96600                  118500
                max                     96600                  129447

Nation                                                                 \
Winners                     Borussia Dortmund                 Hamburg
Attendance      count                       1                       1
                unique                    NaN                     NaN
                top                       NaN                     NaN
                freq                      NaN                     NaN
                mean                    59000                   73500
                std                       NaN                     NaN
                min                     59000                   73500
                25%                     59000                   73500
                50%                     59000                   73500
                75%                     59000                   73500
                max                     59000                   73500
Runner-UpNation count                       1                       1
                unique                      1                       1
                top                     Italy                   Italy
                freq                        1                       1
                mean                      NaN                     NaN
                std                       NaN                     NaN
                min                       NaN                     NaN
                25%                       NaN                     NaN
                50%                       NaN                     NaN
                75%                       NaN                     NaN
                max                       NaN                     NaN
Runners-up      count                       1                       1
                unique                      1                       1
                top                  Juventus                Juventus
                freq                        1                       1
                mean                      NaN                     NaN
                std                       NaN                     NaN
                min                       NaN                     NaN
                25%                       NaN                     NaN
...                                       ...                     ...
Season          freq                        1                       1
                mean                      NaN                     NaN
                std                       NaN                     NaN
                min                       NaN                     NaN
                25%                       NaN                     NaN
                50%                       NaN                     NaN
                75%                       NaN                     NaN
                max                       NaN                     NaN
Venue           count                       1                       1
                unique                      1                       1
                top     Olympiastadion,Munich  Olympic Stadium,Athens
                freq                        1                       1
                mean                      NaN                     NaN
                std                       NaN                     NaN
                min                       NaN                     NaN
                25%                       NaN                     NaN
                50%                       NaN                     NaN
                75%                       NaN                     NaN
                max                       NaN                     NaN

In [217]:
winnersGrp.groups

{('England', 'Aston Villa'): Int64Index([26], dtype='int64'),
 ('England', 'Chelsea'): Int64Index([56], dtype='int64'),
 ('England', 'Liverpool'): Int64Index([21, 22, 25, 28, 49], dtype='int64'),
 ('England', 'Manchester United'): Int64Index([12, 43, 52], dtype='int64'),
 ('England', 'Nottingham Forest'): Int64Index([23, 24], dtype='int64'),
 ('France', 'Marseille'): Int64Index([37], dtype='int64'),
 ('Germany', 'Bayern Munich'): Int64Index([18, 19, 20, 45, 57], dtype='int64'),
 ('Germany', 'Borussia Dortmund'): Int64Index([41], dtype='int64'),
 ('Germany', 'Hamburg'): Int64Index([27], dtype='int64'),
 ('Italy', 'Internazionale'): Int64Index([8, 9, 54], dtype='int64'),
 ('Italy', 'Juventus'): Int64Index([29, 40], dtype='int64'),
 ('Italy', 'Milan'): Int64Index([7, 13, 33, 34, 38, 47, 51], dtype='int64'),
 ('Netherlands', 'Ajax'): Int64Index([15, 16, 17, 39], dtype='int64'),
 ('Netherlands', 'Feyenoord'): Int64Index([14], dtype='int64'),
 ('Netherlands', 'PSV Eindhoven'): Int64Index([32], dtype='int64'),
 ('Portugal', 'Benfica'): Int64Index([5, 6], dtype='int64'),
 ('Portugal', 'Porto'): Int64Index([31, 48], dtype='int64'),
 ('Romania', 'Steaua Bucure?ti'): Int64Index([30], dtype='int64'),
 ('Scotland', 'Celtic'): Int64Index([11], dtype='int64'),
 ('Spain', 'Barcelona'): Int64Index([36, 50, 53, 55], dtype='int64'),
 ('Spain',
  'Real Madrid'): Int64Index([0, 1, 2, 3, 4, 10, 42, 44, 46], dtype='int64'),
 ('Yugoslavia', 'Red Star Belgrade'): Int64Index([35], dtype='int64')}

In [238]:
goalStatsDF=pd.read_csv('data/goal_stats_euro_leagues_2012-13.csv')
#goalStatsDF=goalStatsDF.set_index('Month')
goalStatsDF

         Month           Stat    EPL  La Liga  Serie A  Bundesliga
0   08/01/2012  MatchesPlayed   20.0       20     10.0        10.0
1   09/01/2012  MatchesPlayed   38.0       39     50.0        44.0
2   10/01/2012  MatchesPlayed   31.0       31     39.0        27.0
3   11/01/2012  MatchesPlayed   50.0       41     42.0        46.0
4   12/01/2012  MatchesPlayed   59.0       39     39.0        26.0
5   01/01/2013  MatchesPlayed   42.0       40     40.0        18.0
6   02/01/2013  MatchesPlayed   30.0       40     40.0        36.0
7   03/01/2013  MatchesPlayed   35.0       38     39.0        36.0
8   04/01/2013  MatchesPlayed   42.0       42     41.0        36.0
9   05/01/2013  MatchesPlayed   33.0       40     40.0        27.0
10  06/02/2013  MatchesPlayed    NaN       10      NaN         NaN
11  08/01/2012    GoalsScored   57.0       60     21.0        23.0
12  09/01/2012    GoalsScored  111.0      112    133.0       135.0
13  10/01/2012    GoalsScored   95.0       88     97.0        77.0
14  11/01/2012    GoalsScored  121.0      116    120.0       137.0
15  12/01/2012    GoalsScored  183.0      109    125.0        72.0
16  01/01/2013    GoalsScored  117.0      121    104.0        51.0
17  02/01/2013    GoalsScored   87.0      110    100.0       101.0
18  03/01/2013    GoalsScored   91.0      101     99.0       106.0
19  04/01/2013    GoalsScored  105.0      127    102.0       104.0
20  05/01/2013    GoalsScored   96.0      109    102.0        92.0
21  06/01/2013    GoalsScored    NaN       80      NaN         NaN

In [233]:
goalStatsDF.index

Index(['08/01/2012', '09/01/2012', '10/01/2012', '11/01/2012', '12/01/2012',
       '01/01/2013', '02/01/2013', '03/01/2013', '04/01/2013', '05/01/2013',
       '06/02/2013', '08/01/2012', '09/01/2012', '10/01/2012', '11/01/2012',
       '12/01/2012', '01/01/2013', '02/01/2013', '03/01/2013', '04/01/2013',
       '05/01/2013', '06/01/2013'],
      dtype='object', name='Month')

In [236]:
goalStatsDF=goalStatsDF.reset_index()
goalStatsDF
m=goalStatsDF['Month']
year=lambda x: x.split('/')

year(m[2])

['10', '01', '2012']

In [22]:
m=goalStatsDF['Month']
year=lambda x: x.split('/')[2]
#year(m[1])
goalStatsDF['Year']=m.apply(year,1)
goalStatsDF.head()

        Month           Stat   EPL  La Liga  Serie A  Bundesliga  Year
0  08/01/2012  MatchesPlayed  20.0       20     10.0        10.0  2012
1  09/01/2012  MatchesPlayed  38.0       39     50.0        44.0  2012
2  10/01/2012  MatchesPlayed  31.0       31     39.0        27.0  2012
3  11/01/2012  MatchesPlayed  50.0       41     42.0        46.0  2012
4  12/01/2012  MatchesPlayed  59.0       39     39.0        26.0  2012

In [239]:
y=goalStatsDF['Month']
year=lambda x : x.split('/')[2]
years=[]
for i in range(len(y)):
    years.append(year(y[i]))
goalStatsDF['Year']=years
    
goalStatsDF

         Month           Stat    EPL  La Liga  Serie A  Bundesliga  Year
0   08/01/2012  MatchesPlayed   20.0       20     10.0        10.0  2012
1   09/01/2012  MatchesPlayed   38.0       39     50.0        44.0  2012
2   10/01/2012  MatchesPlayed   31.0       31     39.0        27.0  2012
3   11/01/2012  MatchesPlayed   50.0       41     42.0        46.0  2012
4   12/01/2012  MatchesPlayed   59.0       39     39.0        26.0  2012
5   01/01/2013  MatchesPlayed   42.0       40     40.0        18.0  2013
6   02/01/2013  MatchesPlayed   30.0       40     40.0        36.0  2013
7   03/01/2013  MatchesPlayed   35.0       38     39.0        36.0  2013
8   04/01/2013  MatchesPlayed   42.0       42     41.0        36.0  2013
9   05/01/2013  MatchesPlayed   33.0       40     40.0        27.0  2013
10  06/02/2013  MatchesPlayed    NaN       10      NaN         NaN  2013
11  08/01/2012    GoalsScored   57.0       60     21.0        23.0  2012
12  09/01/2012    GoalsScored  111.0      112    133.0       135.0  2012
13  10/01/2012    GoalsScored   95.0       88     97.0        77.0  2012
14  11/01/2012    GoalsScored  121.0      116    120.0       137.0  2012
15  12/01/2012    GoalsScored  183.0      109    125.0        72.0  2012
16  01/01/2013    GoalsScored  117.0      121    104.0        51.0  2013
17  02/01/2013    GoalsScored   87.0      110    100.0       101.0  2013
18  03/01/2013    GoalsScored   91.0      101     99.0       106.0  2013
19  04/01/2013    GoalsScored  105.0      127    102.0       104.0  2013
20  05/01/2013    GoalsScored   96.0      109    102.0        92.0  2013
21  06/01/2013    GoalsScored    NaN       80      NaN         NaN  2013

In [240]:
goalStatsDF=pd.read_csv('data/goal_stats_euro_leagues_2012-13.csv')
goalStatsDF['Year']=goalStatsDF['Month'].apply(lambda x: x.split('/')[2],1)
goalStatsDF=goalStatsDF.set_index('Month')
goalStatsDF.head()

                     Stat   EPL  La Liga  Serie A  Bundesliga  Year
Month
08/01/2012  MatchesPlayed  20.0       20     10.0        10.0  2012
09/01/2012  MatchesPlayed  38.0       39     50.0        44.0  2012
10/01/2012  MatchesPlayed  31.0       31     39.0        27.0  2012
11/01/2012  MatchesPlayed  50.0       41     42.0        46.0  2012
12/01/2012  MatchesPlayed  59.0       39     39.0        26.0  2012

In [241]:
YearsGrp =goalStatsDF.groupby('Year')
YearsGrp.groups

{'2012': Index(['08/01/2012', '09/01/2012', '10/01/2012', '11/01/2012', '12/01/2012',
        '08/01/2012', '09/01/2012', '10/01/2012', '11/01/2012', '12/01/2012'],
       dtype='object', name='Month'),
 '2013': Index(['01/01/2013', '02/01/2013', '03/01/2013', '04/01/2013', '05/01/2013',
        '06/02/2013', '01/01/2013', '02/01/2013', '03/01/2013', '04/01/2013',
        '05/01/2013', '06/01/2013'],
       dtype='object', name='Month')}

In [242]:
goalStatsDF.head(3)
goalStatsDF.tail(3)

                   Stat    EPL  La Liga  Serie A  Bundesliga  Year
Month
04/01/2013  GoalsScored  105.0      127    102.0       104.0  2013
05/01/2013  GoalsScored   96.0      109    102.0        92.0  2013
06/01/2013  GoalsScored    NaN       80      NaN         NaN  2013

In [243]:
for name, group in YearsGrp:
    print (name)
    print (group)

2012
                     Stat    EPL  La Liga  Serie A  Bundesliga  Year
Month
08/01/2012  MatchesPlayed   20.0       20     10.0        10.0  2012
09/01/2012  MatchesPlayed   38.0       39     50.0        44.0  2012
10/01/2012  MatchesPlayed   31.0       31     39.0        27.0  2012
11/01/2012  MatchesPlayed   50.0       41     42.0        46.0  2012
12/01/2012  MatchesPlayed   59.0       39     39.0        26.0  2012
08/01/2012    GoalsScored   57.0       60     21.0        23.0  2012
09/01/2012    GoalsScored  111.0      112    133.0       135.0  2012
10/01/2012    GoalsScored   95.0       88     97.0        77.0  2012
11/01/2012    GoalsScored  121.0      116    120.0       137.0  2012
12/01/2012    GoalsScored  183.0      109    125.0        72.0  2012
2013
                     Stat    EPL  La Liga  Serie A  Bundesliga  Year
Month
01/01/2013  MatchesPlayed   42.0       40     40.0        18.0  2013
02/01/2013  MatchesPlayed   30.0       40     40.0        36.0  2013
03/01/2013  MatchesPlayed   35.0       38     39.0        36.0  2013
04/01/2013  MatchesPlayed   42.0       42     41.0        36.0  2013
05/01/2013  MatchesPlayed   33.0       40     40.0        27.0  2013
06/02/2013  MatchesPlayed    NaN       10      NaN         NaN  2013
01/01/2013    GoalsScored  117.0      121    104.0        51.0  2013
02/01/2013    GoalsScored   87.0      110    100.0       101.0  2013
03/01/2013    GoalsScored   91.0      101     99.0       106.0  2013
04/01/2013    GoalsScored  105.0      127    102.0       104.0  2013
05/01/2013    GoalsScored   96.0      109    102.0        92.0  2013
06/01/2013    GoalsScored    NaN       80      NaN         NaN  2013

In [244]:
goalStatsGroupedByMonth = goalStatsDF.groupby(level=0)
for name, group in goalStatsGroupedByMonth:
    print (name)
    print (group)
    print ("\n")

01/01/2013
                     Stat    EPL  La Liga  Serie A  Bundesliga  Year
Month
01/01/2013  MatchesPlayed   42.0       40     40.0        18.0  2013
01/01/2013    GoalsScored  117.0      121    104.0        51.0  2013


02/01/2013
                     Stat   EPL  La Liga  Serie A  Bundesliga  Year
Month
02/01/2013  MatchesPlayed  30.0       40     40.0        36.0  2013
02/01/2013    GoalsScored  87.0      110    100.0       101.0  2013


03/01/2013
                     Stat   EPL  La Liga  Serie A  Bundesliga  Year
Month
03/01/2013  MatchesPlayed  35.0       38     39.0        36.0  2013
03/01/2013    GoalsScored  91.0      101     99.0       106.0  2013


04/01/2013
                     Stat    EPL  La Liga  Serie A  Bundesliga  Year
Month
04/01/2013  MatchesPlayed   42.0       42     41.0        36.0  2013
04/01/2013    GoalsScored  105.0      127    102.0       104.0  2013


05/01/2013
                     Stat   EPL  La Liga  Serie A  Bundesliga  Year
Month
05/01/2013  MatchesPlayed  33.0       40     40.0        27.0  2013
05/01/2013    GoalsScored  96.0      109    102.0        92.0  2013


06/01/2013
                   Stat  EPL  La Liga  Serie A  Bundesliga  Year
Month
06/01/2013  GoalsScored  NaN       80      NaN         NaN  2013


06/02/2013
                     Stat  EPL  La Liga  Serie A  Bundesliga  Year
Month
06/02/2013  MatchesPlayed  NaN       10      NaN         NaN  2013


08/01/2012
                     Stat   EPL  La Liga  Serie A  Bundesliga  Year
Month
08/01/2012  MatchesPlayed  20.0       20     10.0        10.0  2012
08/01/2012    GoalsScored  57.0       60     21.0        23.0  2012


09/01/2012
                     Stat    EPL  La Liga  Serie A  Bundesliga  Year
Month
09/01/2012  MatchesPlayed   38.0       39     50.0        44.0  2012
09/01/2012    GoalsScored  111.0      112    133.0       135.0  2012


10/01/2012
                     Stat   EPL  La Liga  Serie A  Bundesliga  Year
Month
10/01/2012  MatchesPlayed  31.0       31     39.0        27.0  2012
10/01/2012    GoalsScored  95.0       88     97.0        77.0  2012


11/01/2012
                     Stat    EPL  La Liga  Serie A  Bundesliga  Year
Month
11/01/2012  MatchesPlayed   50.0       41     42.0        46.0  2012
11/01/2012    GoalsScored  121.0      116    120.0       137.0  2012


12/01/2012
                     Stat    EPL  La Liga  Serie A  Bundesliga  Year
Month
12/01/2012  MatchesPlayed   59.0       39     39.0        26.0  2012
12/01/2012    GoalsScored  183.0      109    125.0        72.0  2012

In [250]:
goalStatsDF=goalStatsDF.reset_index()
#goalStatsDF
goalStatsDF=goalStatsDF.set_index(['Month','Stat'])
goalStatsDF
monthStatGroup=goalStatsDF.groupby(level=['Month','Stat'])
#for name, group in monthStatGroup:
    #print (name)
    #print (group)

In [252]:
goalStatsDF2=pd.read_csv('data/goal_stats_euro_leagues_2012-13.csv')
goalStatsDF2=goalStatsDF2.set_index(['Month','Stat'])
print (goalStatsDF2.head(3))

                           EPL  La Liga  Serie A  Bundesliga
Month      Stat
08/01/2012 MatchesPlayed  20.0       20     10.0        10.0
09/01/2012 MatchesPlayed  38.0       39     50.0        44.0
10/01/2012 MatchesPlayed  31.0       31     39.0        27.0

In [253]:
grouped2=goalStatsDF2.groupby(level='Stat')
grouped2.sum()

                  EPL  La Liga  Serie A  Bundesliga
Stat
GoalsScored    1063.0     1133   1003.0       898.0
MatchesPlayed   380.0      380    380.0       306.0

In [254]:
goalStatsDF2.sum(level='Stat')

                  EPL  La Liga  Serie A  Bundesliga
Stat
GoalsScored    1063.0     1133   1003.0       898.0
MatchesPlayed   380.0      380    380.0       306.0

In [255]:
totalsDF=grouped2.sum()
totalsDF.loc['GoalsScored']/totalsDF.loc['MatchesPlayed']

EPL           2.797368
La Liga       2.981579
Serie A       2.639474
Bundesliga    2.934641
dtype: float64

In [259]:
gpg=totalsDF.loc['GoalsScored']/totalsDF.loc['MatchesPlayed']
gpg
goalsPerGameDF=pd.DataFrame(gpg).T
goalsPerGameDF

        EPL   La Liga   Serie A  Bundesliga
0  2.797368  2.981579  2.639474    2.934641

In [260]:
goalsPerGameDF=goalsPerGameDF.rename(index={0:'GoalsPerGame'})
goalsPerGameDF

                   EPL   La Liga   Serie A  Bundesliga
GoalsPerGame  2.797368  2.981579  2.639474    2.934641

In [48]:
#pd.options.display.float_format='{:.2f}'.format
totalsDF.append(goalsPerGameDF)

                       EPL      La Liga      Serie A  Bundesliga
GoalsScored    1063.000000  1133.000000  1003.000000  898.000000
MatchesPlayed   380.000000   380.000000   380.000000  306.000000
GoalsPerGame      2.797368     2.981579     2.639474    2.934641

In [261]:
#grouped2=goalStatsDF2.groupby(level='Stat')
grouped2.sum()

                  EPL  La Liga  Serie A  Bundesliga
Stat
GoalsScored    1063.0     1133   1003.0       898.0
MatchesPlayed   380.0      380    380.0       306.0

In [262]:
grouped2.aggregate(np.sum)

                  EPL  La Liga  Serie A  Bundesliga
Stat
GoalsScored    1063.0     1133   1003.0       898.0
MatchesPlayed   380.0      380    380.0       306.0

In [263]:
grouped2.agg([np.sum, np.mean,np.size])

                  EPL              La Liga                  Serie A         \
                  sum   mean  size     sum        mean size     sum   mean
Stat
GoalsScored    1063.0  106.3  11.0    1133  103.000000   11  1003.0  100.3
MatchesPlayed   380.0   38.0  11.0     380   34.545455   11   380.0   38.0

                    Bundesliga
               size        sum  mean  size
Stat
GoalsScored    11.0      898.0  89.8  11.0
MatchesPlayed  11.0      306.0  30.6  11.0

In [264]:
goalStatsDF2=pd.read_csv('data/goal_stats_euro_leagues_2012-13.csv')
goalStatsDF2

         Month           Stat    EPL  La Liga  Serie A  Bundesliga
0   08/01/2012  MatchesPlayed   20.0       20     10.0        10.0
1   09/01/2012  MatchesPlayed   38.0       39     50.0        44.0
2   10/01/2012  MatchesPlayed   31.0       31     39.0        27.0
3   11/01/2012  MatchesPlayed   50.0       41     42.0        46.0
4   12/01/2012  MatchesPlayed   59.0       39     39.0        26.0
5   01/01/2013  MatchesPlayed   42.0       40     40.0        18.0
6   02/01/2013  MatchesPlayed   30.0       40     40.0        36.0
7   03/01/2013  MatchesPlayed   35.0       38     39.0        36.0
8   04/01/2013  MatchesPlayed   42.0       42     41.0        36.0
9   05/01/2013  MatchesPlayed   33.0       40     40.0        27.0
10  06/02/2013  MatchesPlayed    NaN       10      NaN         NaN
11  08/01/2012    GoalsScored   57.0       60     21.0        23.0
12  09/01/2012    GoalsScored  111.0      112    133.0       135.0
13  10/01/2012    GoalsScored   95.0       88     97.0        77.0
14  11/01/2012    GoalsScored  121.0      116    120.0       137.0
15  12/01/2012    GoalsScored  183.0      109    125.0        72.0
16  01/01/2013    GoalsScored  117.0      121    104.0        51.0
17  02/01/2013    GoalsScored   87.0      110    100.0       101.0
18  03/01/2013    GoalsScored   91.0      101     99.0       106.0
19  04/01/2013    GoalsScored  105.0      127    102.0       104.0
20  05/01/2013    GoalsScored   96.0      109    102.0        92.0
21  06/01/2013    GoalsScored    NaN       80      NaN         NaN

In [265]:
uefaDF=pd.read_csv('data/euro_winners.csv')
uefaDF.head()

,Season,Nation,Winners,Score,Runners-up,Runner-UpNation,Venue,Attendance
0,1955–56,Spain,Real Madrid,4–3,Stade de Reims,France,"Parc des Princes,Paris",38239
1,1956–57,Spain,Real Madrid,2–0,Fiorentina,Italy,"Santiago Bernabéu Stadium, Madrid",124000
2,1957–58,Spain,Real Madrid,3–2,Milan,Italy,"Heysel Stadium,Brussels",67000
3,1958–59,Spain,Real Madrid,2–0,Stade de Reims,France,"Neckarstadion,Stuttgart",72000
4,1959–60,Spain,Real Madrid,7–3,Eintracht Frankfurt,Germany,"Hampden Park,Glasgow",127621

In [267]:
uefaDF.describe(include="all")

,Season,Nation,Winners,Score,Runners-up,Runner-UpNation,Venue,Attendance
count,58,58,58,58,58,58,58,58.000000
unique,58,10,22,21,33,14,29,NaN
top,2007–08,Spain,Real Madrid,1–0,Bayern Munich,Italy,"Wembley Stadium,London",NaN
freq,1,13,9,15,5,14,7,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66460.482759
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19261.993554
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26732.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53086.500000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63700.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73497.500000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,127621.000000

In [ ]:
uefaDF["Venue"].replace(, ['dot', '\1stuff'], regex=True)

In [268]:
df.replace?

In [279]:
#uefaDF.to_csv('data/euro_winners1111.csv')
uefaDF111=pd.read_csv('data/euro_winners1111.csv',encoding="GBK")
uefaDF111.head()

,Unnamed: 0,Season,Nation,Winners,Score,Runners-up,Runner-UpNation,Venue,Attendance
0,0,1955–56,Spain,Real Madrid,4–3,Stade de Reims,?France,"Parc des Princes,Paris",38239
1,1,1956–57,Spain,Real Madrid,2–0,Fiorentina,Italy,"Santiago Bernabéu Stadium,?Madrid",124000
2,2,1957–58,Spain,Real Madrid,3–2,Milan,Italy,"Heysel Stadium,Brussels",67000
3,3,1958–59,Spain,Real Madrid,2–0,Stade de Reims,?France,"Neckarstadion,Stuttgart",72000
4,4,1959–60,Spain,Real Madrid,7–3,Eintracht Frankfurt,Germany,"Hampden Park,Glasgow",127621

In [274]:
?pd.read_csv

In [340]:
dd=pd.read_csv('data/hz_weather.csv')
dd.describe(include="all").T

     count unique         top freq     mean      std  min  25%   50%  75%  max
日期     118    118  2017-03-19    1      NaN      NaN  NaN  NaN   NaN  NaN  NaN
最高气温   118    NaN         NaN  NaN  15.5424  6.38995    6   11  14.5   19   31
最低气温   118    NaN         NaN  NaN  7.35593  5.13497   -3    4     7   11   21
天气     118      8          多云   44      NaN      NaN  NaN  NaN   NaN  NaN  NaN
风向     118      7          北风   32      NaN      NaN  NaN  NaN   NaN  NaN  NaN
风力     118      7          2级   41      NaN      NaN  NaN  NaN   NaN  NaN  NaN

In [351]:
results=dd.风力.value_counts().reset_index()
results["温度均值差"]=np.nan
results

  index  风力  温度均值差
0    2级  41    NaN
1    3级  29    NaN
2    1级  26    NaN
3    4级  16    NaN
4    5级   2    NaN
5    6级   2    NaN
6    微风   2    NaN

In [359]:
dd1=dd.astype("object")
dd1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 6 columns):
日期      118 non-null object
最高气温    118 non-null object
最低气温    118 non-null object
天气      118 non-null object
风向      118 non-null object
风力      118 non-null object
dtypes: object(6)
memory usage: 5.6+ KB

In [360]:
dd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 6 columns):
日期      118 non-null object
最高气温    118 non-null int64
最低气温    118 non-null int64
天气      118 non-null object
风向      118 non-null object
风力      118 non-null object
dtypes: int64(2), object(4)
memory usage: 5.6+ KB